ipsilon/evmone

- include/evmone/evmone.h
- lib/evmone/evmone.cpp
Can squash commits if needed. Most of this is from Hera.
> Make public header compatible with C 

- test/benchmarks/benchmarks.cpp
use like: `test/evmone-bench codefile.hex calldatahex expectedreturnhex`
```
~/evmone/build# test/evmone-bench sha1code.hex 1605782b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006010203040506  5d211bad8f4ee70e16c7d343a838fc344a1ed961000000000000000000000000 --benchmark_filter=bench_evm_code
```
> benchmark function that gets code from file and input/expected from command args

- test/unittests/evm_calls_test.cpp
- test/unittests/evm_state_test.cpp
> Add tests checking state access patterns

- test/unittests/evm_calls_test.cpp
- test/unittests/evm_fixture.hpp
- test/unittests/evm_state_test.cpp
- test/unittests/evm_test.cpp
> unittests: Use MockedHost by composition

- lib/evmone/analysis.cpp
- lib/evmone/execution.cpp
- lib/evmone/instructions.cpp
All these are included via `analysis.hpp`.
> Remove unneeded includes

- test/unittests/evm_calls_test.cpp
- test/unittests/evm_fixture.hpp
- test/unittests/evm_other_test.cpp
- test/unittests/evm_state_test.cpp
- test/unittests/evm_test.cpp
> test: Refactor EVM unit test fixture

- README.md
> readme: Correct the threading model name

- CHANGELOG.md
> changelog: Add released notes for 0.2

- circle.yml
> ci: Run State Tests

- lib/evmone/analysis.cpp
I had this stray change in my local branch.
> Use intx::as_bytes

- cmake/Hunter/config.cmake
> build: Upgrade intx to 0.5.0

- CMakeLists.txt
- cmake/Hunter/config.cmake
- intx to 0.5.1
- ethash to 0.6.0
> cmake: Upgrade dependencies

- test/bench/CMakeLists.txt
- test/bench/bench.cpp
- test/bench/helpers.hpp
> bench: Extract and improve benchmarking helpers

- lib/evmone/baseline.cpp
- lib/evmone/baseline.hpp
That'll allow to integrate baseline interpreter into [Silkworm](https://github.com/torquem-ch/silkworm/blob/master/core/silkworm/execution/evm.cpp#L208).
> baseline: Allow executing with external state

- lib/evmone/baseline.cpp
- lib/evmone/instruction_traits.hpp
- lib/evmone/instructions.cpp
- lib/evmone/instructions.hpp
- test/unittests/evm_test.cpp
- test/utils/bytecode.hpp
https://github.com/ethereum/evmc/releases/tag/v8.0.0
> Upgrade EVMC to 8.0.0

- lib/evmone/CMakeLists.txt
- lib/evmone/baseline.cpp
- lib/evmone/baseline.hpp
- lib/evmone/vm.cpp
- lib/evmone/vm.hpp
This adds `evmone::VM` class where we can store additional data (e.g. configuration options).
> Add evmone::VM class

- lib/evmone/instructions.hpp
Small cleanup highlighted by https://lgtm.com/projects/g/torquem-ch/silkworm
> NumTopics is size_t and cannot be negative

- circle.yml
- cmake/Hunter/config.cmake
- ethash: 0.6.0 -> 0.7.0
- intx:   0.7.0 -> 0.8.0
> cmake: Upgrade dependencies: intx & ethash

- lib/evmone/baseline.cpp
- lib/evmone/instruction_traits.hpp
If instruction base gas cost is constant across EVM revisions, use the inlined constant in the code directly (no table lookup).
Also change the order of requirements checks: check the stack first. This also helps performance.
> baseline: Use constant gas check if possible

- lib/evmone/baseline.cpp
- lib/evmone/execution_state.hpp
> Refactoring and clean-ups

- lib/evmone/baseline.cpp
Create release_inline attribute which forces function inline only in non-Debug builds. This greatly improves Baseline performance built with GCC.
> baseline: Reintroduce always_inline to Release builds

- lib/evmone/baseline.cpp
#425 will use it to optimize PUSH instructions a bit.
> baseline: Always pad code with 33 bytes

- lib/evmone/instructions.hpp
With 32+ code padding it is aways safe to up to 32 bytes when loading push data. The partial word can always be read as 8 bytes + bswap + shift.
TODO:
> baseline: Optimize PUSH instructions

- lib/evmone/advanced_analysis.hpp
- lib/evmone/advanced_instructions.cpp
- lib/evmone/baseline.cpp
- lib/evmone/execution_state.hpp
- lib/evmone/instructions.hpp
- test/unittests/execution_state_test.cpp
This mostly moved Advanced-only parts of execution state and instruction to Advanced's files.
> Refactor execution state

- circle.yml
Upgrade Silkworm to the latest commit.
And tests to v10.4.
> ci: Upgrade Silkworm

- lib/evmone/baseline.cpp
Didn't do any benchmarks (yet).
> baseline: merge a duplicate if statement

- circle.yml
- cmake/Hunter/config.cmake
Depends on https://github.com/chfast/intx/pull/283.
> ci: Add 32-bit Windows builds

- lib/evmone/advanced_execution.cpp
- lib/evmone/baseline.cpp
- lib/evmone/eof.cpp
- lib/evmone/eof.hpp
- test/eofparse/eofparse.cpp
- test/eofparsefuzz/eofparsefuzz.cpp
- test/unittests/analysis_test.cpp
- test/unittests/eof_test.cpp
> eof: Use container term consistently

- lib/evmone/instructions_traits.hpp
- test/integration/CMakeLists.txt
- test/statetest/statetest_loader.cpp
- test/unittests/instructions_test.cpp
> Support Cancun and Prague revisions in state tests

- test/internal_benchmarks/build_complete_tree.py
Fix typo in /test/internal_benchmarks/build_complete_tree.py
> Fix typo in build_complete_tree.py

- test/unittests/instructions_test.cpp
Pulled out of #563. Also changed the comment according to @chfast's request.
> test: Add instruction_only_in_evmone() helper in instructions_test

- .clang-tidy
- circle.yml
- test/bench/bench.cpp
- test/state/host.cpp
- test/statetest/statetest_loader.cpp
- test/unittests/analysis_test.cpp
- test/unittests/eof_test.cpp
- test/unittests/eof_validation_test.cpp
- test/unittests/execution_state_test.cpp
- test/unittests/state_bloom_filter_test.cpp
- test/unittests/state_mpt_hash_test.cpp
- test/unittests/state_mpt_test.cpp
- test/unittests/state_rlp_test.cpp
Apply changes suggested by clang-tidy-15.
> Modernize test utils

- lib/evmone/instructions.hpp
> Add copy_cost() helper for memory copying gas cost

- lib/evmone/execution_state.hpp
- lib/evmone/instructions_calls.cpp
- test/state/host.cpp
- test/state/host.hpp
- test/unittests/state_transition_create_test.cpp
- test/utils/bytecode.hpp
Requires https://github.com/ethereum/evmc/pull/699
> Lookup CREATE4 tx initcodes by hash

- circle.yml
> ci: Upgrade execution tests to v13.1

- test/state/host.cpp
Don't look up the new account 3x in `Host::create()`, add helper function `is_create_collision()`.
> state: Refactor `Host::create()`

- test/unittests/state_transition.cpp
- Clean up test assert messages.
- Do not modify the post-state storage with map [] operator.
- Better handle non-existent accounts.
> test: Refactor state_transition post checks

- circle.yml
~~Cherrypicked containerKind support from #943~~
>  ci: EOF execution-spec-tests 1.0.5 

- test/unittests/state_transition_create_test.cpp
Add tests for EIP-7610 behavior: create address colliding with an account having non-empty storage should fail.
> test: Add tests for create collision with storage

- test/state/host.cpp
This is needed to prepare for EIP-7702 https://github.com/ethereum/evmone/pull/961
The main goal is to get rid of assertion that requires `recipient == code_address` in case `kind == EVMC_CALL`. (In 7702 world CALL can have `code_address` pointing to a different (delegate) address.)
The idea is to split a variable `dst_acc` that was containing either `recepient` or `code_address` account into two separate variables for each thing.
> Refactor Host::execute_message() to allow CALLs with recipient != code_address

- test/state/state.cpp
Change to the spec from https://github.com/ethereum/EIPs/pull/8938
> EIP-7702: Check that nonce is not max value

- .gdbinit
- gdb_pretty_printers.py
Most probably these are not compatible with LLDB :disappointed:
> Add GDB pretty printers for common bytes and uint256 types

- test/unittests/eof_validation_test.cpp
Fix RJUMPI opcode number in eof1_embedded_container_invalid, and update data section id
> tests: Fix RJUMPI opcode number and update data section id

- lib/evmone/eof.hpp
This improves the quality of the `has_full_data()` EOF helper implementation.
> eof: Improve `has_full_data()` helper

- circle.yml
- test/state/system_contracts.hpp
Update system contract addresses.
> Update EEST tests to pectra-devnet-6

- test/t8n/t8n.cpp
Fixes https://github.com/ethereum/evmone/issues/1130.
> t8n: Skip system contracts if --state.reward=-1

- lib/evmone/eof.cpp
This reduces EOF validation time up to 15%, most significantly in max nested containers benchmarks.
```
Comparing o/eof to o/eof-opt
Benchmark                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------
eof_validation/max_code_sections_pvalue                      0.0036          0.0027      U Test, Repetitions: 9 vs 9
eof_validation/max_code_sections_mean                       -0.0137         -0.0137            95            94            95            94
eof_validation/max_code_sections_median                     -0.0118         -0.0115            95            94            95 …
```
> eof: Optimize allocations when validating the header

- circle.yml
- ethereum/tests: v17.0
- EEST EOF: v2.3.0
> ci: Update test packages

- circle.yml
Update the docker image and ghr tool in the deploy job.
> ci: Update the deploy job

- lib/evmone_precompiles/bn254.hpp
- test/unittests/evmmax_bn254_pairing_test.cpp
Resolves https://github.com/ethereum/evmone/issues/1202
> precompile: Add extended explanation for pairing check API

- lib/evmone/instructions_calls.cpp
- test/state/errors.hpp
- test/state/host.cpp
- test/state/state.cpp
- test/statetest/statetest_export.cpp
- test/unittests/state_transition_eof_create_test.cpp
- test/unittests/state_tx_test.cpp
Updates according to:
- https://github.com/ethereum/EIPs/pull/9669
- ~~https://github.com/ethereum/EIPs/pull/9688~~ EDIT: dropped, keeping CREATE/CREATE2 failures light
> eof: creation tx hard fail on EOF initcode

- circle.yml
- Upgrade ethereum/tests to v17.1
- Upgrade EEST to v4.5.0
> ci: Upgrade execution tests (incl. EEST)

- circle.yml
- test/state/precompiles.cpp
Update the [EIP-7883 "ModExp Gas Cost Increase"](https://eips.ethereum.org/EIPS/eip-7883) to the latest revision:
- https://github.com/ethereum/EIPs/pull/9855
- https://github.com/ethereum/EIPs/pull/9969
> Update modexp precompile costs (EIP-7883)
