ipsilon/evmone

CMakeLists.txt, lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/instructions.cpp
```
Comparing results/master to results/new
sha1_shifts/empty                 -0.1163         -0.1163            53            47            53            47
sha1_shifts/1351                  -0.1393         -0.1393          1031           888          1031           888
sha1_shifts/2737                  -0.1386         -0.1386          2006          1728          2006          1728
sha1_shifts/5311                  -0.1390         -0.1390          3908          3365          3908          3365
sha1_shifts/65536                 -0.1399         -0.1399         47639 …
```
=> New stack implementation

CHANGELOG.md, CMakeLists.txt, README.md, test/CMakeLists.txt, test/unittests/CMakeLists.txt, test/unittests/evm_fixture.hpp, test/unittests/main.cpp, test/unittests/vm_loader.hpp, test/unittests/vm_loader_evmone.cpp, test/utils/CMakeLists.txt
This adds EVM testing tool for EVMC-compatible VM implementations.
It is build out of generic evmone execution tests.
E.g.
```
evm-test ./aleth-interpreter.so
```
Do not confuse with evmone-unittests which contains these test + internal unit tests and has evmone linked "statically".
The name `evmone-test` was also considered.
TODO:
=> EVM test tool

lib/evmone/analysis.cpp, test/unittests/evm_test.cpp
Without the fix it's not only UBSAN warning, but also the test fails, returning `EVMC_OUT_OF_GAS` instead of `EVMC_UNDEFINED_INSTRUCTION`.
Overflow happens not at the place of fix but later during execution here
https://github.com/ethereum/evmone/blob/47a1d47ae96b19a247d3923311735cce118a347b/lib/evmone/instructions.cpp#L1164
=> Fix integer overflow in analysis around gas cost of undefined instruction

test/unittests/bytecode_test.cpp, test/utils/bytecode.hpp
Adds a procedure to convert a bytecode into a human-readable bytecode expression which is also compilable  back to bytecode with bytecode helpers.
TODO:
=> utils: Decode bytecode into human-readable string

lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/instructions.cpp
```
Comparing bin/evmone-bench-base to bin/evmone-bench
sha1_shifts/empty                 -0.0650         -0.0650            49            46            49            46
sha1_shifts/1351                  -0.0841         -0.0841           933           855           933           855
sha1_shifts/2737                  -0.0843         -0.0843          1817          1664          1817          1664
sha1_shifts/5311                  -0.0838         -0.0838          3541          3244          3541          3244
sha1_shifts/65536                 -0.0837         -0.0838 …
```
=> Rework main loop iteration

test/bench/CMakeLists.txt, test/bench/bench.cpp
```bash
evmone-bench <evmc_module> <path_to_benchmarks_dir>
```
=> bench: Add option to load external EVMC VM

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/instructions.cpp, test/unittests/analysis_test.cpp, test/utils/dump.cpp
This replaces the linear search if the jumpdest with binary search. It also applies data-driven approach where the jumpdest "map" is not vector of pairs, but two vectors of offsets and targets. We also shrank the size of elements from `int` to `int16_t`.
There is a small trade-off here. The analysis takes longer because requires 2x more vector resizes. And for contracts with small number of jumpdests (like blake2b_huff which only has 3 of them) the time increase in analysis might hide the gain in execution. But still I believe it's worth the 33% speed increase in blake2b_shifts which has a lot of jumpdests.
``` …
```
=> Speed up finding jumpdests

lib/evmone/CMakeLists.txt, lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/opcodes_helpers.h, test/unittests/evm_test.cpp
```
Benchmark                          Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------
sha1_shifts/analysis            -0.1639         -0.1638             4             3             4             3
stop/analysis                   -0.1656         -0.1656             0             0             0             0
blake2b_huff/analysis           -0.1537         -0.1536            41            35            41            35
sha1_divs/analysis              -0.1559         -0.1559             4             4             4             4
weierstrudel/analysis           -0.1504         -0.1504            49 …
```
=> Analysis optimization - use switch()

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/instructions.cpp, lib/evmone/opcodes_helpers.h, test/unittests/analysis_test.cpp
This contains some micro-optimization, but is mostly about using `uint64_t` as a storage for push values for small pushes (up to `PUSH8`).
```
sha1_shifts/analysis              +0.0444         +0.0444             3             3             3             3
sha1_shifts/empty                 -0.0734         -0.0734            40            37            40            37
sha1_shifts/1351                  -0.0903         -0.0903           750           682           750           682
sha1_shifts/2737 …
```
=> Push values optimisation

lib/evmone/analysis.cpp, lib/evmone/instructions.cpp
For DUPs, SWAPs and LOGs, we now use different methods and eliminate the need for additional function parameter. For DUPs and SWAPs methods generated by templates. This solution was slightly faster than extracting common code. For LOGs, we have a common code handling all cases.
```
sha1_shifts/analysis              -0.0090         -0.0090             3             3             3             3
sha1_shifts/empty                 -0.0156         -0.0156            37            37            37            37 …
```
=> Eliminate parameters of some instructions

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/instructions.cpp, test/unittests/analysis_test.cpp, test/utils/dump.cpp
This information is only needed in analysis to compute other block stack requirements parameters.
=> Do not keep information about block stack change

test/unittests/evm_test.cpp
Tests extracted from https://github.com/ethereum/evmone/pull/113
Without EIP-663 implementation result in Petersburg and Istanbul is the same.
=> Tests demonstrating unlimited SWAP/DUP problem with jumpdests

cmake/Hunter/config.cmake, cmake/Hunter/init.cmake, lib/evmone/instructions.cpp
This is to see new intx API in usage. The intx PR: https://github.com/chfast/intx/pull/107.
It also uses `intx::addmod()` and `intx::mulmod()`. Closes #110.
I didn't expect it to perform any better, but it does.
Skylake CPU:
```
blake2b_huff/analysis             -0.0006         -0.0003            75            75            75            75
blake2b_huff/empty                -0.0003         -0.0001           111           111           111           111
blake2b_huff/abc                  +0.0013         +0.0015 …
```
=> Use new BE API from intx

lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/instructions.cpp
This changes the signature of functions implementing instructions and the main loop. The pointer to current instructions has been removed from the state object, is now passed as an argument (rdi register) and next instruction pointer is returned from the instruction function (rax register).
```
sha1_shifts/analysis              -0.0018         -0.0018             4             4             4             4
sha1_shifts/empty                 -0.0626         -0.0626            37            35            37 …
```
=> Always keep current instruction pointer in a register

test/unittests/evm_fixture.hpp
Fix #146 
We can't dereference the bytes_view data pointer in execute() since the pointer might not be valid (for example, when empty code is supplied). Instead, we should just retrieve the pointer and pass it to the VM's "execute" implementation.
=> Update test fixture to properly handle empty code

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/instructions.cpp, test/bench/bench.cpp, test/unittests/analysis_test.cpp
I believe the `instruction_table` is more precise name, but `op_table` is shorter and might be less mistaken with the table of instructions in the loaded program.
=> Drop op_table parameter in analysis()

lib/evmone/analysis.cpp, test/unittests/analysis_test.cpp
Requires https://github.com/ethereum/evmone/pull/166.
Refactors analysis to have new block creation in single place. It also removes some unneeded variables and code.
TODO
Bechmarks:
```
Benchmark                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------
blake2b_huff/analysis                           -0.0866         -0.0866            37            34            37            34
blake2b_shifts/analysis                         -0.0941         -0.0940            20            18            20            18
sha1_divs/analysis …
```
=> Analysis refactoring

CMakeLists.txt, test/CMakeLists.txt, test/fuzzer/CMakeLists.txt, test/fuzzer/fuzzer.cpp
This is not build on CI. This might be done later. But I'm using this code locally all the time and is quite stable now (I rarely do changes there) so it's good time to put it in the repo finally.
cc @cryptomental
=> fuzzer: Add evmone-fuzzer for EVMC VMs

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, lib/evmone/instructions.cpp, test/unittests/analysis_test.cpp, test/utils/dump.cpp
=> Block info optimization

lib/evmone/analysis.cpp
This also makes it faster.
Skylake Mobile:
```
Benchmark                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------
blake2b_huff/analysis                           -0.1002         -0.1002            28            25            28            25
blake2b_shifts/analysis                         -0.2091         -0.2090            15            12            15            12
sha1_divs/analysis                              -0.0715         -0.0714             3             3             3             3
sha1_shifts/analysis                            -0.1620 …
```
=> Make small push value parsing endianness independent

test/unittests/op_table_test.cpp
I saw this test failing (on my CHAINID branch) and wanted to know what exactly was failing.
=> Improve error messages in op_table.compare_with_evmc_instruction_tables test

test/fuzzer/CMakeLists.txt, test/fuzzer/README.md, test/fuzzer/fuzzer.cpp
Change the license of evmone-fuzzer from Apache 2.0 to GPL 3.0.
This is required because evmone-fuzzer "links to" aleth-interpreter (GPL 3.0).
=> fuzzer: Correct the LICENSE

circle.yml
Related to #192 
I added 32-bit build to circle.yml as given in [https://github.com/ethereum/evmc/blob/master/circle.yml#L149-L158](https://github.com/ethereum/evmc/blob/master/circle.yml#L149-L158), with some differences. I built it using `cmake .. -DEVMONE_TESTING=ON` command, followed by `cmake --build . -- -j` and then ran `bin/evmone-unittests` to test it.
No error/warnings were seen during the execution of these three commands. Have I tested it correctly?
=> Add 32-bit gcc support

test/unittests/evm_test.cpp
This originally was to simplify some of the stack requirements preprocessing, but the change was incorrect. A unit test was added to show I was wrong.
=> tests: Extend the stack_underflow unit test

CHANGELOG.md, lib/evmone/instructions.cpp, test/unittests/evm_state_test.cpp
This is a variant of CHAINID implementation that uses current EVMC `master`, which defines chain ID as `evmc_uint256be`
Based on separate PR that updates EVMC https://github.com/ethereum/evmone/pull/189
A version that uses 64 bit chain ID was in https://github.com/ethereum/evmone/pull/164
=> CHAINID opcode - 256 bit version

CHANGELOG.md, lib/evmone/instructions.cpp, test/unittests/evm_state_test.cpp, test/unittests/evm_test.cpp
Ref https://eips.ethereum.org/EIPS/eip-1884
Need to actually add all the changes to EVMC apparently.
=> Implement SELFBALANCE opcode from EIP-1884

lib/evmone/analysis.cpp, lib/evmone/instructions.cpp, test/unittests/evm_state_test.cpp
https://github.com/ethereum/EIPs/pull/2200
=> Implement EIP-2200

lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/execution.hpp, test/bench/bench.cpp
This is proof the release candidate of EVMC 7.0.0 is ok.
=> Upgrade EVMC to version 7.0.0

README.md, docs/efficient_gas_calculation_algorithm.md
=> article: Efficient gas calculation algorithm for EVM

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, test/unittests/evm_other_test.cpp, test/utils/dump.cpp
This mostly affects the performance of the analysis, but I think this change must land. Is much better if we are not restricted by the code size in general (i.e. evmone works for any code size).
This do not fix all the issues. There are other case not related to the jumpdest where overflow can happen. That is to be fixed in other PRs.
```
Benchmark                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------
blake2b_huff/analysis                           +0.0051         +0.0051            26            26            26            26
blake2b_huff/empty …
```
=> Fix jumpdest offset overflow

lib/evmone/analysis.cpp, lib/evmone/analysis.hpp, test/unittests/analysis_test.cpp, test/unittests/evm_other_test.cpp
This avoids overflow when calculating a block gas cost using saturation to `UINT_MAX`. To reach the limit you now need a block of 400k instructions and 4G of gas.
=> Fix block gas cost overflow

.clang-format, test/bench/bench.cpp, test/fuzzer/fuzzer.cpp, test/unittests/bytecode_test.cpp, test/unittests/evm_calls_test.cpp, test/unittests/evm_fixture.hpp, test/unittests/evm_test.cpp, test/unittests/utils_test.cpp, test/utils/bytecode.hpp, test/utils/utils.cpp, test/utils/utils.hpp
- Clean ups #includes in utils
- Preallocates bytes buffer.
- Renames `to_hex()` to `hex()` (last commit, so can be reviewed separately).
=> utils: Cleanups

CHANGELOG.md, appveyor.yml
NATIVE=ON for MSVC enables AVX instruction set. This make Windows release binaries unusable on CPUs not having AVX.
=> ci: Drop -DNATIVE=ON for Windows builds

circle.yml
The testeth 1.8.0 expects empty stEWASMTests dir.
=> ci: Hotfix State tests execution

README.md, appveyor.yml
The Visual Studio 2017 crashes when compiling #268.
=> Drop Visual Studio 2017 support

lib/evmone/CMakeLists.txt, lib/evmone/instruction_traits.hpp, lib/evmone/instructions.cpp, test/unittests/op_table_test.cpp
Convert instruction metrics to compile-time traits. The traits can then be used to construct efficient implementation-specific instruction tables.
=> Refactor instruction tables, add compile-time information

lib/evmone/CMakeLists.txt, lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, lib/evmone/evmone.cpp, test/bench/bench.cpp, test/unittests/evm_fixture.cpp, test/unittests/evmone_test.cpp
The "baseline" is a new interpreter added to evmone. It has much simpler, "classic" design and performs minimal amount of code analysis (only required JUMPDEST analysis, the code is unmodified). EVM instructions implementations are shared with "advanced" VM where possible.
To use it pass `O=0` option.
The initial benchmarking results look promising (see below). All done with Clang-11 compiler. The GCC-10 has lower performance, but I believe this can be fixed.
Moreover, the first PoC has some additional changes and tweaks (e.g. custom instruction table) and is up to 5% faster than this version. The old version is still available in [baseline-old](https://github.com/ethereum/evmone/tree/baseline-old) branch.
For solidity test suite it performs a tinny bit better.
```
Performance counter …
```
=> Baseline interpreter

README.md
I also created #279 which should be converted to `docs/optimization.md` over time.
=> readme: Describe Advanced and Baseline interpreters

test/bench/CMakeLists.txt, test/bench/bench.cpp
This improves CLI handling in `evmone-bench` slightly, but this remains very messy piece of code.
The main goal is to allow skipping loading benchmarks from a dir. Here this can be achieve by passing `""` dirname, but #278 may want to allowing omitting the arg.
=> bench: Modernize CLI parsing, ignore empty args

test/bench/CMakeLists.txt, test/bench/bench.cpp, test/bench/synthetic_benchmarks.cpp, test/bench/synthetic_benchmarks.hpp
See: https://notes.ethereum.org/@chfast/benchmarking-evm-instructions
=> EVM instructions synthetic benchmarks

lib/evmone/instructions.cpp
Sort the order of initialization of the instruction_implementations
table and fix duplicate initialization of OP_EXTCODEHASH.
=> Sort initialization of instruction_implementations

circle.yml, lib/evmone/baseline.cpp, lib/evmone/instruction_traits.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip2929_test.cpp, test/unittests/evm_fixture.hpp
Recreation of https://github.com/ethereum/evmone/pull/289 because GutHub decided to close it for no reason.
=> EIP-2929: Gas cost increases for state access opcodes

lib/evmone/baseline.cpp
Optimize the build_jumpdest_map() procedure for JUMPDEST analysis.
- "is push opcode" conditions has been changed to (op & 0xE0) == 0x60.
- the op == JUMPDEST condition has been marked as unlikely.
=> Optimize JUMPDEST analysis

lib/evmone/baseline.cpp
Optimize the build_jumpdest_map() procedure by comparing opcode as
signed integer and eliminating always true op <= OP_PUSH32 (0x7f) check.
=> Optimize build_jumpdest_map()

lib/evmone/analysis.hpp, lib/evmone/execution.cpp, lib/evmone/execution.hpp, test/unittests/execution_state_test.cpp
Change the execute API for Advanced interpreter to map the Baseline API.
The new API requires to provide the execution state object (user can
make better decision how to allocate it) and the code analysis (it is
bound to the code itself so user can cache them together).
=> Provide better execute() C++ API

test/bench/helpers.hpp
This allows using state-access instructions in benchmarks. Previously
such benchmarks would crash.
=> bench: Run execution benchmarks with MockedHost

lib/evmone/CMakeLists.txt, lib/evmone/baseline.cpp, lib/evmone/tracing.hpp, lib/evmone/vm.hpp, test/unittests/CMakeLists.txt, test/unittests/tracing_test.cpp
With the templated implementation there is no change in the performance. Without a template, the overhead can be up to 10%.
The `Tracer` interface is:
```cpp
class Tracer
{ 
virtual void on_execution_start(
evmc_revision rev, const evmc_message& msg, bytes_view code) noexcept = 0;
virtual void on_instruction_start(uint32_t pc) noexcept = 0;
virtual void on_execution_end(const evmc_result& result) noexcept = 0;
};
```
It can be extended/modified easily depending on needs of the practical tracer implementations.
=> Add tracing infrastructure to Baseline interpreter

lib/evmone/baseline.cpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.cpp, lib/evmone/instructions.hpp, test/unittests/execution_state_test.cpp
This adds some simple inspection methods to `Stack` and `Memory` types needed for tracing.
=> State types extensions for tracing

CMakeLists.txt
Disable runtime stack protection (-fstack-protector). It does not
compile well to WebAssembly. ASan can detect the same issues.
=> cmake: Disable stack protection (-fstack-protector)

cmake/Hunter/config.cmake
Build only ethash::keccak library.
=> cmake: Upgrade ethash to 0.7.0

circle.yml, lib/evmone/baseline.cpp, lib/evmone/instruction_traits.hpp, lib/evmone/instructions.cpp, lib/evmone/instructions.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip3198_basefee_test.cpp
EVMC change: https://github.com/ethereum/evmc/pull/603.
=> Implement EIP-3198: BASEFEE opcode

lib/evmone/CMakeLists.txt, lib/evmone/baseline.cpp, lib/evmone/tracing.cpp, lib/evmone/tracing.hpp, lib/evmone/vm.cpp, test/integration/CMakeLists.txt, test/unittests/tracing_test.cpp
Implementation of EVM tracing following the [EIP-3155](https://eips.ethereum.org/EIPS/eip-3155) (draft). It outputs log line with JSON (jsonl) for every instruction to standard error output.
Differences from the spec:
1. All calls start with non-standard "start call" log: 
```json
{"kind":"call","static":false,"depth":0,"rev":"Berlin"}
```
2. All calls end with non-standard "end call" log as a replacement for single _summerical info_ at the end of transaction execution.
```json
{"error":null,"gas":964766,"gasUsed":35234,"output":"da39a3ee5e6b4b0d3255bfef95601890afd80709000000000000000000000000"}
```
- the `"stateRoot"` is omitted as there is no way to compute it,
- the `"error"` is taken from the instruction trace log, replaces `"pass"` or `"successful"`.
3. The `"gasCost"` is omitted. …
=> Instruction tracing with EIP-3155 JSONL output

appveyor.yml, lib/evmone/execution.cpp
triggered in MSVC debug build (Visual Studio 2019 version 16.10)
=> advanced: Prevent invalid memory subscript index

lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, test/bench/helpers.hpp
During code analysis the code is copied and padded with 33 zero bytes. This guarantees that push data is always available in the code buffer and the code ends with STOP. This allows optimizing the interpreter loop and PUSH instructions.
Performance gains are up to ~5%.
This is also needed to enable other optimization: implementing interpreter with "computed goto" or "tail calls".
=> Optimize Baseline interpreter by using padded code

lib/evmone/baseline.hpp, lib/evmone/execution.hpp, test/bench/CMakeLists.txt, test/bench/bench.cpp, test/bench/helpers.hpp, test/bench/synthetic_benchmarks.cpp
For Advanced and Baseline builtin VMs this adds "execute" benchmarks which uses cached code analysis and pre-allocated execution state to much usage pattern in Ethereum clients (like Silkworm).
The existing EVMC-like execution has been renamed to "total" as it performs analysis and execution in each iteration.
=> bench: Add separate benchmarks for execution only

lib/evmone/CMakeLists.txt, lib/evmone/baseline.cpp, lib/evmone/baseline_instruction_table.cpp, lib/evmone/baseline_instruction_table.hpp
Previously EVMC instruction tables were used (for quick head start).
Now two EVMC tables are replaced with single one. This at least cuts memory bandwidth from 12 bytes to 4 bytes per instruction.
Changes to instruction requirements checks are minimal but the stack overflow is checked differently.
The check can be further optimized but this will be done separately.
=> baseline: Use custom instruction table

cmake/Hunter/config.cmake, lib/evmone/instructions.hpp, test/unittests/evm_test.cpp
[intx 0.6.0](https://github.com/chfast/intx/releases/tag/v0.6.0)
Haswell 4.0 GHz, clang-12
```
Comparing o/main-master to o/main-intx06
Benchmark                                                                Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------------
advanced/execute/main/blake2b_huff/empty_mean                         +0.0172         +0.0172            13            13            13            13
baseline/execute/main/blake2b_huff/empty_mean                         -0.0001         -0.0001            16            16            16            16
advanced/execute/main/blake2b_huff/2805nulls_mean …
```
=> Upgrade intx to 0.6.0

lib/evmone/baseline_instruction_table.cpp, lib/evmone/baseline_instruction_table.hpp, lib/evmone/instruction_traits.hpp, lib/evmone/instructions.cpp, test/unittests/op_table_test.cpp
Instead of using template specialization `instr::gas_costs<Revision>[op]` convert the instr::gas_costs to multi-dimensional array `instr::gas_costs[Revision][op]`.
The immediate benefit is ability to loop over all revision at compile-time - lower instruction table generation maintenance.
=> Convert instr::gas_costs to multi-dimentional array

lib/evmone/baseline.cpp
- Add two generic dispatch implementation macros: DISPATCH() and DISPATCH_NEXT().
- Get rid of common ++pc code for some instruction.
=> baseline: "Inline" ++pc

lib/evmone/baseline.cpp
The "pc" name for a pointer/iterator is confusing because in other
places (including the PC instruction) the "pc" means the code offset.
=> baseline: Rename pc to code_it

circle.yml, lib/evmone/analysis.hpp, lib/evmone/baseline.cpp, lib/evmone/execution.cpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.cpp, test/unittests/execution_state_test.cpp
Add pointer to code analysis to ExecutionState to unify signature of instruction implementations.
=> Uniform access to code analysis via ExecutionState

lib/evmone/baseline.cpp, lib/evmone/instructions.hpp
This introduces new "more unified" instruction implementation signature which receives current PC and returns new PC. Allows implementing PUSH, JUMP and JUMPI instructions.
=> Return new pc from instruction implementation

test/internal_benchmarks/find_jumpdest_bench.cpp
This is a set of basic improvements to `find_jumpdest` benchmark suite.
I also tried not inlining implementations, but I'm not sure this is reasonable.
The `_random` benchmarks may be more what we want to benchmark. If yes, we may want to drop other ones.
=> bench: Improvements to find_jumpdest benchmarks

CHANGELOG.md, circle.yml, lib/evmone/baseline.cpp, test/unittests/evm_test.cpp
To handle invalid jump the implementation targets the byte just after
the official code length. For padded code this byte may be uninitialized
push data causing unpredictable behavior. The fix is to also init this
byte to OP_STOP.
The bug was detected in https://github.com/torquem-ch/silkworm/issues/305.
Here two simple unit tests were added which are able to detect the core issue in MSVC/ASan/memcheck builds.
=> baseline: Fix incorrect exit after invalid jump

lib/evmone/instructions.hpp, test/unittests/evm_test.cpp
Rework implementations of `BYTE` and `SAR` to make its code size smaller. The `BYTE` now has branchless implementation. The `SAR` is still not inlined by is 33% smaller by assembly lines.
=> Optimize BYTE and SAR for code size

lib/evmone/baseline.cpp, lib/evmone/instructions.cpp, lib/evmone/instructions.hpp, test/unittests/evm_test.cpp
Add StopToken type as a status code wrapper to indicate instructions
unconditionally terminating execution.
=> Add StopToken type

circle.yml, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/unittests/evm_calls_test.cpp, test/unittests/evm_eip2929_test.cpp, test/unittests/evm_fixture.hpp, test/unittests/evm_state_test.cpp, test/unittests/evm_test.cpp
See https://github.com/torquem-ch/silkworm/pull/286 for the original discussion.
Consensus tests pass with https://github.com/torquem-ch/silkworm/pull/288.
=> Use code_address member from evmc_message (EVMC 10.0.0-alpha.1)

lib/evmone/instructions.hpp
- Small optimization to how huge offset/size is checked.
- Most importantly, "grow memory" moved to separate noinline function. This helps clang-13 compiler to make better decision about inlining `check_memory()` and further `MLOAD`, `MSTORE` and `MSTORE8` instructions.
=> Optimize memory check/grow

lib/evmone/execution_state.hpp
```
advanced/execute/main/blake2b_huff/empty_mean                          -0.0304         -0.0304            13            12            13            12                                                                            
baseline/execute/main/blake2b_huff/empty_mean                          -0.0117         -0.0117            15            15            15            15                                                                            
advanced/execute/main/blake2b_huff/2805nulls_mean                      -0.0381         -0.0381           279           269           279           269                                                                            
baseline/execute/main/blake2b_huff/2805nulls_mean                      -0.0081         -0.0081           334 …
```
=> memory: Use realloc() to grow memory

lib/evmone/advanced_execution.cpp, lib/evmone/advanced_instructions.cpp, lib/evmone/baseline.cpp, lib/evmone/instructions.hpp
Advanced can easily wrap also generic instruction implementations with `StopToken`.
=> advanced: Reuse more generic instructions

lib/evmone/advanced_instructions.cpp, lib/evmone/baseline.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/unittests/evm_test.cpp
Introduce instruction "core" implementations which differ by not
adjusting EVM stack height. Also provide wrappers (instr::impl<Op>)
to support previous instruction functions.
Use "core" instructions in Baseline.
=> Introduce instruction "core" implementations

lib/evmone/baseline.cpp
The attribute makes clang debug builds to use excessive amount of stack
space and consensus testing is not working any more in existing configs.
The removal of the attribute does not affect optimized builds.
Fixes #422.
=> baseline: Drop [[always_inline]] from invoke()

lib/evmone/baseline.cpp, lib/evmone/tracing.cpp, lib/evmone/tracing.hpp, test/unittests/tracing_test.cpp
Track EVM stack top item outside of State object. This make the stack
top pointer always visible to the compiler and it is able to better
optimize the interpreter.
=> baseline: Track stack evolution separately

lib/evmone/execution_state.hpp
Place the Stack field of ExecutionState in the end. It in-place
allocates the stack space so this improves ExecutionState layout:
all individual members are in front sharing cache lines and theirs
memory offsets are smaller. Also the struct padding is optimal.
=> Move stack space allocation in ExecutionState back

circle.yml
=> ci: Upgrade Clang coverage build to clang 13.0.1

lib/evmone/CMakeLists.txt, lib/evmone/advanced_execution.cpp, lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, test/bench/helpers.hpp, test/unittests/CMakeLists.txt, test/unittests/analysis_test.cpp, test/unittests/eof_test.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_test.cpp, test/utils/bytecode.hpp
[Make EOF header validation more generic (supporting any sections)](https://github.com/ethereum/evmone/pull/334/commits/b7ef61abaee316c716f805467584c48841fb2a99) commit is an optional refactoring, than will make adding new sections easier in the future.
=> EOF execution and validation (EIP-3540)

lib/evmone/advanced_analysis.cpp, lib/evmone/advanced_instructions.cpp, test/unittests/analysis_test.cpp, test/unittests/evm_test.cpp
=> Advanced: Basic block metadata placement refactoring

lib/evmone/advanced_execution.cpp, lib/evmone/eof.cpp, test/unittests/analysis_test.cpp
The main addition is the [readability-container-data-pointer](https://clang.llvm.org/extra/clang-tidy/checks/readability-container-data-pointer.html) check. I think in some place the `&v[0]` is more meaningful than `v.data()` so we can disable the check.
=> Fix clang-tidy 14 warnings

lib/evmone/advanced_instructions.cpp, test/unittests/evm_control_flow_test.cpp
Fix stack height check for the basic block following a JUMPI instruction.
Before the stack height was 1 too big because the implementation
incorrectly did not remove the JUMPI condition from the stack.
The bug was introduced in https://github.com/ethereum/evmone/pull/457.
=> advanced: Fix JUMPI followed by stack underflow

CMakeLists.txt, circle.yml
Bump the minimum required CMake version to 3.16. This is already fact
because required by ethash. Also specify max version 3.23 for policy
settings.
=> cmake: Require CMake 3.16

.clang-tidy, test/state/CMakeLists.txt, test/state/hash_utils.hpp, test/state/mpt.cpp, test/state/mpt.hpp, test/unittests/CMakeLists.txt, test/unittests/state_mpt_test.cpp, test/utils/utils.hpp
Add insert-only Merkle Patricia Trie implementation for computing MTP root hashes of (key, value) maps.
=> state: Add insert-only MPT implementation

lib/evmone/CMakeLists.txt, lib/evmone/instructions.hpp, lib/evmone/instructions_storage.cpp
The storage instructions (SLOAD, SSTORE) have complex gas cost model
and are gas-expensive by themselves. So there are no benefits of
inlining their implementations. Moreover, we are going to introduce
some cost lookup tables for SSTORE so it is better to have a separate
file for it.
=> Move storage instructions implementations to .cpp

lib/evmone/advanced_execution.cpp, lib/evmone/baseline.cpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, lib/evmone/instructions_storage.cpp, test/unittests/evm_calls_test.cpp, test/unittests/evm_state_test.cpp, test/unittests/evm_storage_test.cpp, test/utils/bytecode.hpp
Calculate, aggregate and report the gas refund. This requires changes to `SSTORE`, `SELFDESTRUCT` and calls (propagate gas refund).
=> Implement gas refund

lib/evmone/advanced_instructions.cpp, lib/evmone/baseline.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_xmacro.hpp, lib/evmone/vm.cpp, lib/evmone/vm.hpp, test/bench/bench.cpp, test/unittests/evm_fixture.cpp, test/unittests/evmone_test.cpp
This finally adds "computed goto" dispatch loop implementation. This is enabled by default for Baseline if a compiler supports the [Labels as Values](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html) extension.
=> Baseline threaded code (computed goto)

lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, test/unittests/execution_state_test.cpp
EOF does not require code padding for execution as executable code must end with terminating instruction.
This also refactors code analysis and execution state.
=> Do not pad code for EOF

CHANGELOG.md, README.md, circle.yml, lib/evmone/CMakeLists.txt, lib/evmone/baseline.cpp, test/bench/CMakeLists.txt, test/bench/bench.cpp, test/statetest/statetest_loader.cpp
Bump the required C++ standard from C++17 to C++20. Use some example C++20 features to adjust the minimal supported compiler versions.
=> cmake: Require C++20

test/state/CMakeLists.txt, test/statetest/CMakeLists.txt
Add `evmone::statetestutils` library, which will be used by #513, since #513 introduces the JSON State Test format for benchmarks.
=> cmake: Add evmone::statetestutils library

circle.yml, test/integration/statetest/CMakeLists.txt, test/statetest/statetest.cpp
Allow passing multiple paths to evmone-statetest to load tests from.
Closes #510
=> statetest: Load tests from multiple dirs/files

circle.yml, test/state/CMakeLists.txt, test/state/account.hpp, test/state/host.cpp, test/state/host.hpp, test/state/precompiles.cpp, test/state/precompiles.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/CMakeLists.txt, test/statetest/statetest.cpp, test/statetest/statetest.hpp, test/statetest/statetest_runner.cpp
This implements state transition as application of a single transaction to a predefined state. Most of the logic is in the `evmc::Host` implementation plus the transaction specific handling in `evmone::state::transition()`.
These are used to execute all tests by the statetest runner.
The precompiles are not implemented.
=> Add implementation of evmc::Host and state transition

lib/evmone/baseline.cpp
Change stack overflow/underflow checks to stack pointers comparisons.
This gives better compiler optimizations. This gives around ~2% performance improvements.
=> baseline: Better stack overflow/underflow checks

lib/evmone/instructions.hpp
Clang compiler generates suboptimal code if the temporary struct is used in SWAP implementation. Workaround it by using 4x uint64_t temporaries.
https://github.com/llvm/llvm-project/issues/59116
=> Optimize SWAP

circle.yml
Require GCC 11 (previously 10) and Clang 13 (previously 11). Earlier versions do not have good C++20 support, in particular the `using enum` feature.
Add xcode-min with Xcode 13.4.1 job to monitor minimal version required.
=> ci: Bump minimal compilers versions

lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, lib/evmone/instructions.hpp, test/unittests/tracing_test.cpp
After #531 tracer gets `state.original_code` and then uses PC value to get an opcode from this code, which is incorrect for EOF.
I don't have a fix yet, but wrote a test.
=> Fix instruction tracing of EOF code

lib/evmone/advanced_instructions.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/CMakeLists.txt, test/unittests/eof_validation_test.cpp, test/unittests/evm_eip663_dupn_swapn_test.cpp, test/unittests/evm_fixture.cpp, test/unittests/evm_fixture.hpp, test/unittests/instructions_test.cpp
https://eips.ethereum.org/EIPS/eip-663
=> Implement EIP-663: Unlimited SWAP and DUP instructions

CMakeLists.txt, cmake/Hunter/init.cmake
- Hunter 0.24.5 → 0.24.11
- intx 0.8.0 → 0.9.0 (performance improvements for GCC)
- GTest 1.11.0 → 1.12.1
=> cmake: Upgrade dependencies

lib/evmone/instructions_calls.cpp
- Perform uint256 → size_t casts of memory offsets and sizes in single
place when it is safe to do so.
- Assume failure of CALL/CREATE by setting result to 0 and clearing
the return buffer before performing any checks.
=> Refactor CALL/CREATE instructions

lib/evmone/instructions_calls.cpp, test/state/host.cpp, test/state/host.hpp, test/state/state.cpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip3860_initcode_test.cpp
=> EIP-3860: Limit and meter initcode

test/CMakeLists.txt, test/state/CMakeLists.txt, test/state/errors.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/CMakeLists.txt, test/t8n/t8n.cpp
The t8n is "state transition" CLI interface used to check and generate
JSON tests. It reads and outputs specified JSON files.
See https://ethereum-tests.readthedocs.io/en/develop/t8ntool-ref.html.
=> Add evmone t8n tool

test/state/state.cpp
Spec: https://eips.ethereum.org/EIPS/eip-3651
Tested with: https://github.com/ethereum/tests/pull/1082.
=> state: Implement EIP-3651: Warm COINBASE

lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/CMakeLists.txt, test/eofparse/CMakeLists.txt, test/eofparse/eofparse.cpp, test/eofparsefuzz/CMakeLists.txt, test/eofparsefuzz/eofparsefuzz.cpp, test/unittests/eof_validation_test.cpp
Pulled this out from #563. Could be merged on its own.
=> Introduce eofparse and eofparsefuzz

lib/evmone/eof.cpp
Pulled out of #563, but not sure who the author is.
=> eof: Change handling of errors from pair<val, err> to variant<val, err>

test/bench/bench.cpp, test/state/state.hpp, test/statetest/statetest.cpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/unittests/CMakeLists.txt, test/unittests/statetest_loader_test.cpp
Refactor JSON test loading procedures to take generic input stream (instead of a file path) to make it easy to create unit tests for them.
=> Make JSON Test Loader unit-testable

test/state/host.cpp, test/state/host.hpp, test/unittests/CMakeLists.txt, test/unittests/state_new_account_address_test.cpp
Refactor `compute_new_account_address()` to match 𝐀𝐃𝐃𝐑 from Yellow Paper.
This makes it a separate utility independent of `evmc_message`.
=> state: Refactor `compute_new_account_address()`

circle.yml
Update Silkworm on CI to its latest commit (this fixes a fatal compiler warning). Also update compiler to GCC 12 and blockchain tests revision.
=> ci: Update Silkworm

test/t8n/t8n.cpp
-`t8n` output files should be formatted in readable string. Not just single line.
=> t8n: Add pretty json output printing

test/t8n/t8n.cpp
- Change is required by `execution-spec-tests`. The tool doesn't set `hash` field for transaction in `txs.json`. We have to calculate it.
- Add better error printing to console.
=> t8n: Add tx hash calculation for tx receipt

test/integration/statetest/CMakeLists.txt, test/integration/statetest/eof/invalid_eof_in_state.json, test/statetest/CMakeLists.txt, test/statetest/statetest_runner.cpp
=> statetest: Validate EOF containers in test state

test/bench/bench.cpp, test/bench/synthetic_benchmarks.cpp
Avoid `-Wshadow` warnings from clang-17. The proper fix is in #596 but we cannot apply it yet due to insufficient compiler support.
=> bench: Fix clang-17 compiler warnings

test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/unittests/CMakeLists.txt, test/unittests/statetest_loader_block_info_test.cpp, test/unittests/statetest_loader_test.cpp, test/unittests/statetest_loader_tx_test.cpp
-Add tests cases for BlockInfo loader according to bugs reported.
-Extend `from_json` implementation for `64` bits integers to support `hex` and `dec` strings and values
-Add special case handling to suport `currentRandom` passed as `0`. `execution-spec-tests` requires it.
=> Load BlockInfo fixes required by exec-spec-tests

test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_block_info_test.cpp
Following Spencer's fix added in https://github.com/ethereum/evmone/pull/602
=> statetest: Fix loading difficulty for BlockInfo

lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/unittests/evm_test.cpp
This is preparation to remove `gas` from `ExecutionState` and passing `gas` by value everywhere.
=> Rework memory grow/check helpers - pass gas counter by value

lib/evmone/baseline.cpp, lib/evmone/tracing.cpp, lib/evmone/tracing.hpp, test/unittests/tracing_test.cpp
Decouple "gas left" from ExecutionState and pass it as separate param.
=> tracing: Separate gas parameter

test/state/rlp.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest_loader.cpp, test/unittests/state_rlp_test.cpp, test/unittests/statetest_loader_tx_test.cpp
-Loading `chainId` from tx json representation.
-Encoding `access_list` to RLP
-Add `access_list` (eip2930) transaction type
=> Add features required to properly calculate transaction hash

circle.yml
Migrates to the new codecov uploader (old one is deprecated).
Good news is that we don't need python any more.
Instead we need to download some "binaries" (project is nodejs based).
We do some integration checks, but I'm not sure how good they are.
I also had to add `CODECOV_TOKEN` to Circle CI. Some docs say it shouldn't be needed for public repos on Circle CI, but upload wasn't working and worked with the token.
=> ci: Switch to new codecov uploader

lib/evmone/advanced_analysis.hpp, lib/evmone/advanced_instructions.cpp, lib/evmone/baseline.cpp, lib/evmone/baseline.hpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, lib/evmone/instructions_storage.cpp, test/bench/helpers.hpp, test/unittests/execution_state_test.cpp
- Pass and return gas counter to instructions implementations by value, don't use `ExecutionState::gas_left`. This improves performance.
- Introduce `Result` type `{status, gas}`.
- Change `StopToken` to `TermResult` (strong alias of `Result`).
- Remove `gas_left` from `ExecutionState`.
=> Pass gas to instructions by value

test/state/CMakeLists.txt, test/state/hash_utils.cpp, test/state/hash_utils.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_control_flow_test.cpp, test/unittests/evm_memory_test.cpp, test/unittests/evm_state_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_create_test.cpp, test/unittests/state_transition_eof_test.cpp, test/utils/bytecode.hpp
Add unit test fixture based on state transition. The fixture is designed in a way the test cases have structure similar to JSON state tests. This should make it easier to export the test cases to JSON format in the future.
=> test: Declarative state transition test suite

test/state/state.cpp, test/state/state.hpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/state_transition.cpp
- Separate selfdestruct handling from empty account clearing.
- Apply block reward to coinbase consistently.
- Use it to properly clean state in `t8n` and `state-test-runner`.
=> state: Clean up state finalization

test/state/state.cpp, test/state/state.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/CMakeLists.txt, test/unittests/state_transition.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/statetest_loader_block_info_test.cpp
- Add support for withdrawals in t8n interface. It's required by `execution-spec-tests`
- Tests
=> Support withdrawals in t8n

circle.yml
Previous "medium" macos machines are deprecated. See https://circleci.com/docs/using-macos/#available-resource-classes.
=> ci: Upgrade to macos.x86.medium.gen2

test/unittests/state_transition.hpp, test/unittests/state_transition_block_test.cpp, test/unittests/state_transition_create_test.cpp
The new address looks a bit nicer.
=> test: Change default state transition test sender

circle.yml, test/statetest/statetest.cpp
EIP/EOF tests enabled.
```
[----------] 2 tests from ori
[ RUN      ] ori.CreateEOF1
[       OK ] ori.CreateEOF1 (2 ms)
[ RUN      ] ori.EOF1ValidInvalid
[       OK ] ori.EOF1ValidInvalid (2 ms)
[----------] 2 tests from ori (5 ms total)
[----------] 12 tests from stEIP3540
[ RUN      ] stEIP3540.CREATE2_EOF1
[       OK ] stEIP3540.CREATE2_EOF1 (1 ms)
[ RUN      ] stEIP3540.CREATE2_EOF1Invalid
[       OK ] stEIP3540.CREATE2_EOF1Invalid (11 ms)
[ RUN      ] stEIP3540.CREATE2_EOF1Invalid_FromEOF
[       OK ] stEIP3540.CREATE2_EOF1Invalid_FromEOF (4 ms)
[ RUN      ] stEIP3540.CREATE2_EOF1_FromEOF
[       OK ] stEIP3540.CREATE2_EOF1_FromEOF (0 ms)
[ RUN      ] stEIP3540.CREATE_EOF1
[       OK ] stEIP3540.CREATE_EOF1 (0 ms)
[ RUN      ] stEIP3540.CREATE_EOF1Invalid
[       OK ] …
```
=> statetest, ci: Update EOF state tests

test/statetest/statetest_loader.cpp
GCC 13 has added new warning "dangling-reference" and it causes a lot of false positives.
See
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109642
- https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=6b927b1297e66e26e62e722bf15c921dcbbd25b9
- https://twitter.com/vzverovich/status/1654845759395893248
=> statetest: Workaround GCC 13 -Wdangling-reference

lib/evmone/eof.cpp, lib/evmone/eof.hpp
This makes EOF validation tests output better failures.
=> Add output operator for EOFValidationError to be used by Google.Test

lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/evm_memory_test.cpp, test/unittests/instructions_test.cpp, test/utils/bytecode.hpp
Implements [EIP-5656: Memory copying instruction](https://eips.ethereum.org/EIPS/eip-5656).
=> Implement MCOPY (EIP-5656)

circle.yml
Modify the CI config and extract the EOF execution tests step. Download EOF state tests from https://github.com/ipsilon/tests branch `eof`. This allows to shorten develop-test loop by delaying the tests upstream step.
=> ci: Take EOF state tests from ipsilon fork

circle.yml
- Pin commit for EOF state tests.
- Upgrade Silkworm to recent main (2b71148).
- Disable Silkworm-driven blockchain tests. Some tests are failing. See #656.
=> ci: Pin commit for EOF state tests, disable blockhain tests

lib/evmone/instructions.hpp
`pop()` returns a reference and we don't need to make an extra copy.
Previous discussion: https://github.com/ethereum/evmone/pull/629#pullrequestreview-1422204520
=> Use references to stack values in MCOPY

circle.yml
Fixes https://github.com/ethereum/evmone/issues/656.
=> ci: Re-enable Silkoworm-driven blockchain tests

test/unittests/evm_calls_test.cpp, test/utils/bytecode.hpp
Introduce returndatasize() and returndatacopy() bytecode helpers and rewrite/extend unit tests for `RETURNDATASIZE` and `RETURNDATACOPY`.
=> test: Modernize `RETURNDATA*` unit tests

lib/evmone/eof.cpp, lib/evmone/instructions_traits.hpp, test/unittests/eof_validation_test.cpp, test/unittests/instructions_test.cpp
Problem fixed: DATALOADN validation was reading the immediate value before checking it's not truncated.
=> Fix DATALOADN truncated immediate validation

lib/evmone/eof.cpp, test/unittests/eof_validation_test.cpp
Based on #663 
Validating immediate argument is of `CALLF` shouldn't be part of stack validation, but rather instruction validation.
`DATALOADN` and `RJUMPV` (`max_offset`) arguments are already validated in `validate_instructions()` and #553 adds `CREATE3` and `RETURNCONTRACT` there too, so it makes sense to have all these similar validations in one place.
=> Move CALLF immediate argument validation to validate_instructions()

circle.yml, lib/evmone/instructions_calls.cpp, test/unittests/CMakeLists.txt, test/unittests/evm_eof_calls_test.cpp
The code targeted by DELEGATECALL from an EOF must also be an EOF.
This restriction has been added to EIP-3540 in
https://github.com/ethereum/EIPs/pull/7131.
=> Reject DELEGATECALL EOF → legacy 

test/state/state.cpp
The withdrawals should be processed before state clearing so the empty accounts touched with 0 value withdrawals are also cleared from the state.
Fixes issue reported by https://github.com/ethereum/execution-spec-tests/pull/142.
=> state: Fix processing withdrawals of 0

circle.yml, cmake/Hunter/config.cmake
https://github.com/chfast/intx/releases/tag/v0.10.1
This fixes the buggy Xcode compiler on arm64.
Fixes https://github.com/ethereum/evmone/issues/655.
=> Upgrade intx to 0.10.1

circle.yml
This is to enable access to important C++20 features:
- `std::bit_cast`,
- ranges.
=> Bump minimal Xcode version to 14.3

circle.yml, lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/instructions.hpp, test/unittests/eof_validation_test.cpp, test/utils/bytecode.hpp
Change according to https://github.com/ethereum/EIPs/pull/6546/files
=> Change RJUMPV immediate argument to max_index

test/state/mpt.cpp, test/unittests/state_mpt_test.cpp
For the branch and extended nodes in Merkle Patricia Trie, when the length of the encoded child is 31 or smaller the hashing of the child node is omitted.
=> MPT: Add support for "short" nodes

test/state/state.cpp, test/state/state.hpp, test/t8n/t8n.cpp, test/unittests/state_mpt_hash_test.cpp
- Encode `cumulative_gas_used` instead of `gas_used`
- Support tx receipt format for pre Byzantium
=> Blockchain tests support: Fix tx receipt rlp encoding

test/unittests/state_mpt_hash_test.cpp
When compiling `code = {0x00}` with GCC 12 -O3 it detects a false positive buffer overflow and gives a warning. Workaround it by using explicit `code = bytes{0x00}`.
```
/usr/include/c++/12/bits/char_traits.h:268:23: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
268 |       __builtin_memcpy(__s1, __s2, __n * sizeof(char_type));
|       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The warning is gone in GCC 13.
=> test: Workaround GCC 12 warning at -O3

lib/evmone/tracing.cpp, lib/evmone/vm.cpp, test/integration/CMakeLists.txt, test/integration/statetest/CMakeLists.txt, test/t8n/t8n.cpp, test/unittests/tracing_test.cpp
Add `--trace` option for `evmone-t8n` to output traces to specific files compatible with `retesteth`.
Modify the tracing format to follow closer the specification at [EIP-3155: EVM trace specification](https://eips.ethereum.org/EIPS/eip-3155).
=> Add tracing output for t8n

test/state/host.cpp, test/state/state.hpp, test/statetest/statetest_loader.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/statetest_loader_block_info_test.cpp
Implement loading JSON `block_number => block_hash` map and expose it to `Host::get_block_hash()` via `BlockInfo`.
=> state: Support block hashes

test/state/mpt_hash.cpp, test/state/mpt_hash.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/t8n/t8n.cpp, test/unittests/CMakeLists.txt, test/unittests/state_mpt_hash_test.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/statetest_withdrawals_test.cpp
- Support withdrawals root hash calculation
- Add `ArrowGlacier` fork name mapping to `evmc_revision` (cast to London fork).
=> Blockchain tests support: Withdrawals hashing

lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_function_test.cpp
- Add validation rule.
- Add unit tests.
- Fix already existing unit test.
=> Check stack height for OP_CALLF validation

test/state/state.cpp, test/unittests/CMakeLists.txt, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_tx_test.cpp, test/unittests/state_tx_test.cpp
Properly handle the case when the account of transaction sender doesn't
exist. In pre-Byzantium revisions such transaction could be valid with
gas price 0. In any case the transaction validation should not crash.
Fixes https://github.com/ethereum/evmone/issues/692.
=> Blockchain tests support: Do not expect tx sender always exist

circle.yml, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/state/account.hpp, test/state/host.cpp, test/state/host.hpp, test/unittests/CMakeLists.txt, test/unittests/instructions_test.cpp, test/unittests/state_transition_transient_storage_test.cpp, test/utils/bytecode.hpp
> EIP-1153: Transient storage opcodes
> Add opcodes for manipulating state that behaves identically to storage but is discarded after every transaction
https://eips.ethereum.org/EIPS/eip-1153
=> Implement EIP-1153: Transient storage

test/state/host.cpp, test/unittests/evm_state_test.cpp, test/unittests/state_transition_block_test.cpp, test/utils/bytecode.hpp
If explict block hashes are not provided, return predefined block hashes from `Host::get_block_hash()` as `keccak256(str(block_number))`. This is badly documented convention used in state tests.
Note: the readability of block hash values from `BLOCKHASH` instruction still applies. I.e. you will get 0 if you ask for a block from the future or more than 256 blocks older than the current one.
=> state: Implement fake `BLOCKHASH` resolution for testing

codecov.yml
Because the Windows CI is currently failing due to under-the-hood MSVC compiler upgrade do not hold Codecov reports.
=> ci: Show codecov report even if CI fails

lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip4844_blobhash_test.cpp, test/unittests/instructions_test.cpp, test/utils/bytecode.hpp
Implement `BLOBHASH` instruction and add support for blob transactions in state tests.
=> Add BLOBHASH instruction

test/unittests/CMakeLists.txt, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_trace_test.cpp
Optionally (when `expect.trace = "<trace string>"`) is used capture the transaction execution trace in state_transition and compare it with the expected one.
Replaces #699.
=> test: Capture the trace of state_transition

test/integration/statetest/CMakeLists.txt, test/integration/statetest/tx/invalid_nonce.json, test/statetest/statetest.cpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/unittests/statetest_loader_test.cpp
- Add `--trace-summary` CLI flag to output state root.
- Make `_info` JSON section optional (goevmlab is not providing this field).
- Implement convention for `Host::get_block_hash()` (done in #698).
=> statetest: Add changes required to be executed in goevmlab

test/state/host.cpp
This enables `BLOBBASEFEE` implementation and fixes small issues with CMake cross-compilation.
=> Upgrade EVMC to 11.0.0-alpha.2

circle.yml, cmake/toolchains/riscv32.cmake, test/integration/CMakeLists.txt
This uses a pre-built RISC-V toolchain to build and test evmone.
This compiles evmone and dependencies to `rv32imafdc` with `ilp32d` ABI. I.e. this target has hardware support for floating point.
Our preference would be to compile for `rv32imac` with `ilp32` ABI. However, there are some obstacles to get there:
1. The pre-built toolchain is built for `ilp32d`. We would need to build the toolchain ourselves.
2. We can hack it by setting `-march=rv32imac -mabi=ilp32d`. The compiler is not very happy about using architecture with incompatible ABI but it will proceed anyway. Unfortunately, the dependencies have some floating-point code so we also need to provide soft-float library. I was not able to make it build so far.
=> Build and test riscv32

test/state/state.cpp
Delete empty accounts after each transaction
and after applying withdrawals and block rewards.
=> state: Delete empty accounts after each tx

test/unittests/state_transition.cpp
When I debug state transition tests, sometimes I want to see the trace even if this assertion fails
```cpp
ASSERT_NE(acc, nullptr) << "account " << addr << " should exist";
```
=> Move trace output earlier in state transition tests

circle.yml, test/CMakeLists.txt, test/blockchaintest/.clang-tidy, test/blockchaintest/CMakeLists.txt, test/blockchaintest/blockchaintest.cpp, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/bloom_filter.cpp, test/state/bloom_filter.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/CMakeLists.txt, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/unittests/CMakeLists.txt, test/unittests/blockchaintest_loader_test.cpp, test/unittests/state_bloom_filter_test.cpp
- Several changes making functions visible for blockchain tests.
- Support different naming of several fields in json format of transaction
- Implement blockchain tests loader and runner
- Add unit test for blockchain test loader
- Invalid tx and blocks are not supported yet
=> Blockchain tests runner

circle.yml, test/state/state.cpp
The transient storage [EIP-1153](https://eips.ethereum.org/EIPS/eip-1153)
must not persist between transactions. Clear the transient storage
attached to every account at the end of transaction execution.
=> Properly clear transient storage after transaction execution

lib/evmone/instructions_traits.hpp
https://github.com/ethereum/EIPs/pull/7803
=> Update DATALOAD/DATALOADN prices

lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip7516_blobbasefee_test.cpp, test/unittests/instructions_test.cpp
Implement `BLOBBASEFEE` instruction from [EIP-7516](https://eips.ethereum.org/EIPS/eip-7516): "BLOBBASEFEE opcode".
=> Implement `BLOBBASEFEE` instruction from EIP-7516

circle.yml
Change conan version to exact (`1.60.2`) one pointed in [silkworm documentation](https://github.com/erigontech/silkworm#building-on-linux--macos)
=> Upgrade conan version required to build silkworm

test/state/host.cpp, test/state/state.cpp, test/unittests/state_transition_create_test.cpp
This change is basically refactoring with the goal not to access the call sender's account unnecessary.
=> host: Don't assume the sender account exists

test/state/host.cpp, test/state/precompiles.cpp, test/state/precompiles.hpp, test/unittests/CMakeLists.txt, test/unittests/state_precompiles_test.cpp
Extract a precompile address recognition into new is_precompile()
function and use it in all places where this information is needed.
Improve maintenance of "precompile ids" by adding aliases to the enum.
Add unit tests for is_precompile().
=> Refactor precompiles detection

CMakeLists.txt, test/state/account.hpp, test/state/state.hpp, test/unittests/state_transition.hpp
This warning is too noisy for C++ designated initializer.
=> cmake: Disable -Wmissing-field-initializers in GCC

test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_test.cpp
- Use designated initializers for big structs like `BlockInfo` and `BlockHeader`. They show how JSON names are mapped to field names and help avoiding complicated merge conflicts.
- Load JSON integers as unsigned values + cast to signed if needed. This workarounds the problem with execution-spec-tests where timestamps can be uint64.
- Omit 0 storage values from state dumps in `evmone-blockchaintest`.
=> test: Improve maintainability of JSON loading

test/state/account.hpp, test/state/host.cpp, test/state/state.cpp, test/unittests/CMakeLists.txt, test/unittests/state_transition_selfdestruct_test.cpp
Implement the EIP-6780 "SELFDESTRUCT only in same transaction".
https://eips.ethereum.org/EIPS/eip-6780
This EIP changes the functionality of the `SELFDESTRUCT` instruction.
The new functionality will be only to send all Ether in the account
to the beneficiary, except that the current behavior is preserved when
`SELFDESTRUCT` is called in the same transaction a contract was created.
=> Implement EIP-6780 "SELFDESTRUCT"

test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/host.cpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest_loader.cpp, test/unittests/CMakeLists.txt, test/unittests/state_system_call_test.cpp
Implement the system call from the "Block processing" of the EIP-4788.
https://eips.ethereum.org/EIPS/eip-4788#block-processing
At the beginning of each block a gas-free call is invoked from
the _system_ account (`0xff..fe`) to the specific _system_ contract.
=> Implement EIP-4788: Beacon block root in the EVM

circle.yml, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/errors.hpp, test/state/host.cpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/CMakeLists.txt, test/unittests/state_block_test.cpp, test/unittests/state_rlp_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/state_transition_tx_test.cpp, test/unittests/state_tx_test.cpp, test/unittests/statetest_loader_block_info_test.cpp, test/unittests/statetest_loader_tx_test.cpp
- Add blob tx type support in state. 
- Modify `transition` and `validate_transaction` functions to pass `blob_gas_left` parameter.
- Update unit tests
- Support blob tx in t8n
- Compute `excess_blob_gas` and `blob_gas_price`.
=> Support blob transaction type (EIP-4844)

test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/unittests/blockchaintest_loader_test.cpp, test/utils/utils.cpp, test/utils/utils.hpp
Add support for blockchain tests with predefined timestamp of a revision transition (e.g. transtion from Shanghai to Cancun at the timestamp of 15000).
=> blockchaintest: Add support for revision transitions

circle.yml
- Upgrade ethereum/tests to v13.
- Download and run execution-spec-tests (v1.0.6).
=> ci: Run execution-spec-tests

lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/unittests/eof_validation_test.cpp
Error `non_empty_stack_on_terminating_instruction` is currently only used when there is a [mismatch between the number of stack items in current function context and the total number of defined outputs](https://github.com/ethereum/evmone/blob/master/lib/evmone/eof.cpp#L421-L422), which is no longer accurate. 
This PR changes the error name to indicate outputs mismatch.
=> Rename error non_empty_stack_on_terminating_instruction

test/integration/statetest/CMakeLists.txt, test/statetest/CMakeLists.txt, test/statetest/statetest.cpp, test/statetest/statetest.hpp, test/statetest/statetest_export.cpp, test/t8n/t8n.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp
Add option to export the "state_transition" test suite to JSON State Test format.
The current version of the export feature has limitations:
- tests with invalid transaction are not exported
- not every test property is properly exported
- some exported tests fail in `evmone-statetest`
=> test: Export state transition tests to JSON

test/unittests/analysis_test.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_calls_test.cpp, test/unittests/evm_eof_function_test.cpp, test/unittests/evm_eof_rjump_test.cpp, test/unittests/evm_eof_test.cpp, test/unittests/evm_memory_test.cpp, test/unittests/state_transition_eof_test.cpp, test/unittests/tracing_test.cpp, test/utils/bytecode.hpp
New builder-like utility in `bytecode.hpp` to generate EOF containers instead of old `eof1_bytecode()` function.
=> EOF bytecode test helper refactor

lib/evmone/eof.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/state/errors.hpp, test/state/host.cpp, test/state/host.hpp, test/state/state.cpp, test/unittests/evm_eof_test.cpp, test/unittests/state_transition_create_test.cpp
- adjusts failure scenarios to new spec after https://github.com/ipsilon/eof/commit/e927c283e881136acb99981190dd4377463e6cd5
- fixes a stack management bug in CREATE4 light failure modes + adds test
- as a bonus it updates the validity rules for `InitcodeTransaction` and adds an `rlp_encode` specialization for it.
Do not merge before [changes to `evmc`](https://github.com/ethereum/evmc/pull/700) are merged (collapsing `EVMC_CREATE3` and `4`)
=> Fix and update CREATE4 failure scenarios

lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/unittests/eof_validation_test.cpp
The only observable change here is that now stack height / outputs mismatch at `RETF` can produce two different errors:
- `stack_underflow` when not enough outputs
- `stack_higher_than_outputs_required` when extra items left on stack.
Before both cases produced `code_section_outputs_mismatch` error.
This makes it consistent with similar cases for `JUMPF`, which already produce these two different errors.
=> Minor cleanup of RETF stack validation

CMakeLists.txt, cmake/Hunter/init.cmake, cmake/cable/HunterGate.cmake, test/bench/bench.cpp, test/bench/synthetic_benchmarks.cpp, test/internal_benchmarks/.clang-tidy, test/internal_benchmarks/memory_allocation.cpp
Bump max CMake compatible version to 3.27. Upgrade Hunter to get new dependencies and fix CMake 3.27 warnings. Clean up compiler warning flags.
=> Compatibility with CMake 3.27

test/state/host.cpp, test/state/state.cpp, test/state/state.hpp
Implement State Journal: a list of changes made to the state
and implement state reverting as undoing the changes until the given
journal checkpoint.
With the State Journal the backup copy of the state is no longer
performed and the memory addresses of the accounts are not changing
during execution. This allows us to avoid some copies and lookups.
=> state: Revert state changes with journal

test/unittests/state_transition_selfdestruct_test.cpp
Add new state transition tests related to SELFDESTRUCT:
- Double selfdestruct of the same account where the later selfdestruct is reverted.
- Tests selfdestructing ~4000 accounts pre/post Cancun/EIP-6780.
=> test: Add more selfdestruct state transition tests

test/unittests/evm_eof_rjump_test.cpp
- Replace CODECOPY with DATACOPY
- Use calldata argument instead of modifying code byte
- Split long jumps case into separate cases for min negative and max positive jumps
=> eof: Improve RJUMPV tests

test/statetest/statetest.cpp
This increase the tracing performance. More info in the C++ spec: https://en.cppreference.com/w/cpp/io/ios_base/sync_with_stdio
=> statetest: Disable sync with stdio when tracing

circle.yml
We need better C++20 support. Clang 15 is also the minimal version for Silkworm currently.
=> ci: Bump minimum supported Clang to 15 (from 13)

lib/evmone/instructions_traits.hpp
This function is not meant to be executed at runtime.
=> Change has_const_gas_cost() to consteval

test/state/host.cpp
Optimize code deployment in "create" by reusing the reference to the new account. The reference remains valid because the state reverts are implemented with the journal.
=> state: Optimize "create" code deployment

CMakeLists.txt, circle.yml
- Upgrade docker images for CI
- Update code coverage tools and scripts
- Use clang-17 as the latest LLVM compiler
Closes #767
=> CI: Build with clang-17

README.md, lib/evmone/baseline.cpp, lib/evmone/vm.cpp, lib/evmone/vm.hpp, test/integration/CMakeLists.txt
Closes #585 
Not sure about placement and API. I assumed it should be off by default, and not concern `evmc` code, this is what I've got as a result.
=> Enable EOF validation before execution in `evmc run`

test/state/mpt.cpp, test/state/mpt.hpp, test/unittests/state_mpt_test.cpp
Some refactoring and improvements to the MPT implementation:
- Refactor Path to behave like standard container.
- Refactor the `Kind` enum and path encoding.
- Change path mismatch handling by using iterators.
=> MPT refactoring

test/utils/bytecode.hpp
- Support decoding all opcodes with imm arguments in `bytecode` library
=> bytecode: Decode opcodes with immediate arguments

test/state/state.cpp, test/state/state.hpp
- Group methods revertible by `rollback()` (only `touch()` for now). We later want to hide the journal from users by providing revertible state modification methods.
- Move `State` methods implementations to the `state.cpp` file. This hides the implementation and allows faster builds.
- Move types related to Journal implementation to the `class State` scope.
=> state: Move pieces of State implemetation

test/state/state.cpp
If an account is being touched but is not empty it doesn't make sense to mark it as touched. Touching only affects deleting empty accounts but an account cannot become empty later during transaction execution (except for selfdestruct, but this is tracked separately).
When executing all state tests from https://github.com/ethereum/tests, this optimization reduces number of registered touch events by 99.2% (from 1673250 to 13806) and number of reverted touch events by 99.7% (from 1345463 to 401).
Moreover, considering current Mainnet status and
[EIP-7523: Empty accounts deprecation](https://eips.ethereum.org/EIPS/eip-7523) empty accounts cannot be encountered after the Paris revision. Therefore, this change total disables unnecessary touch handling in current PoS networks.
=> state: Only mark touch of empty accounts

test/state/state.cpp
(cherry picked from commit 2003cc09970da8121b3a72fdc7a7ce6ce34043ac)
=> Assert `rlp_encode` only for supported tx types

lib/evmone/advanced_analysis.hpp, lib/evmone/advanced_instructions.cpp, lib/evmone/baseline.cpp, lib/evmone/baseline_instruction_table.cpp, lib/evmone/eof.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_traits.hpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eip663_dupn_swapn_test.cpp
Closes #538 
Please take an extra look if the `invoke` specializations added are ok and have no undesired side effects, esp. the `advanced` counterpart. The compiler made me add the latter, even if it's not used.
=> DUPN and SWAPN in EOF only + EOF stack validation

lib/evmone/advanced_instructions.cpp, lib/evmone/baseline_instruction_table.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/evm_calls_test.cpp, test/unittests/instructions_test.cpp, test/utils/bytecode.hpp
Closes #775 
Inclusion is still somewhat pending, but this is likely to be included in the EOF instruction set to avoid code size regressions reported by compiler teams. 
For this reason, I'm opening as draft, but this is reviewable. Does including a new opcode require any additional work?
=> Implement RETURNDATALOAD (EOF)

test/unittests/eof_validation_test.cpp, test/utils/bytecode.hpp
\+ bytecode.hpp helpers for callf/jumpf.
=> Test for circular JUMPF validation

test/state/host.cpp, test/state/host.hpp, test/unittests/state_new_account_address_test.cpp, test/unittests/state_transition_create_test.cpp, test/unittests/tracing_test.cpp
Split the function `compute_new_account_address()` into two:
- `compute_create_address()`
- `compute_create2_address()`.
Use these in the state transition tests to predict the created accounts.
Fixes https://github.com/ethereum/evmone/issues/782.
=> host: Split compute_new_account_address()

test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_create_test.cpp
Add option to check the expected post state MPT root hash of the state_transition tests.
=> test: Option to check state root hash

test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/statetest_loader_test.cpp
Generalize `validate_deployed_code()` to `validate_state()`. It validates an Ethereum state (likely a test pre-state). New added check: disallow zero-value storage entries.
=> test: Generalize `validate_state()`

test/state/ethash_difficulty.cpp, test/unittests/state_difficulty_test.cpp
Applies the minimum difficulty cap also to pre-Byzantium difficulty
calculations.
Fixes https://github.com/ethereum/evmone/issues/752.
=> test: Adjust difficulty if below minimum `0x20000`

test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_test.cpp
In the `validate_state()` also check for unexpected code with EOF prefix before EOF is enabled. The EIP-3541 prevents such code to be deployed.
=> test: Check for unexpected EOF prefix in tests

test/unittests/eof_validation.cpp
=> Output failed test case index in EOF validation tests

circle.yml, lib/evmone/eof.cpp, test/unittests/eof_stack_validation_test.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_rjump_test.cpp
https://notes.ethereum.org/Fk1TksgjTxOotvQNL07mEQ#Less-restricted-validation-algorithm
=> EOF: less restricted stack validation

test/integration/statetest/CMakeLists.txt, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_eof_test.cpp, test/unittests/state_transition_tx_test.cpp, test/utils/utils.cpp
Add support for exporting state transition tests:
- with legacy transactions (pre EIP-1559)
- with access list
- support EVMC spelling of revisions
=> test: Add some mising State Test export features

test/state/host.cpp, test/unittests/state_transition_create_test.cpp
In Frontier when CREATE fails to deploy the code because of the deployment cost the creation behaves as it has been successful although the created account has empty code.
Fix the CREATE instruction by returning the address of the created account instead of the null address.
The gas refund is also applied as in the case of successful code deployment. Geth agrees with this but this situation probably never happened on Mainnet.
=> state: Fix failing code deployment in Frontier

test/unittests/eof_validation.cpp
Reconcile names with the ones used in https://github.com/ethereum/retesteth/pull/225
=> Fix error messages used in exported EOF validation tests

circle.yml, test/utils/utils.cpp
This adds "Paris" and "Petersburg" to the names recognized by the testing utils.
=> test: Recognize all official fork/revision names

test/unittests/CMakeLists.txt, test/unittests/state_transition_call_test.cpp, test/unittests/state_transition_create_test.cpp, test/unittests/state_transition_extcode_test.cpp, test/unittests/state_transition_selfdestruct_test.cpp, test/unittests/state_transition_touch_test.cpp
New tests for:
- contract creation,
- account touches,
- empty coinbase,
- selfdestruct,
- extcode.
These tests come from the work on #802 so may not be very coherent.
=> test: New State transition tests

test/unittests/eof_validation_test.cpp
I was wondering if we had this condition covered in validation and found that possible we were missing one interesting edge case test, where _the first_ section RETFs. Added here. Let me know if this has been covered in tests already and I've missed it
=> Add missing test for RETF in first section

CMakeLists.txt, circle.yml
We want to use `cmake -E cat` added in 3.18.
This is also the version from Debian 11 released in 2021.
=> cmake: Bump minimum required CMake version to 3.18

test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_tx_test.cpp
Throw more meaningful exception in case we cannot parse hex hash from JSON (instead of throwing "bad optional access").
Closes https://github.com/ethereum/evmone/issues/829.
=> test: Improve error of invalid hash in JSON

test/integration/CMakeLists.txt, test/integration/t8n/CMakeLists.txt, test/integration/t8n/cancun_create_tx/alloc.json, test/integration/t8n/cancun_create_tx/env.json, test/integration/t8n/cancun_create_tx/txs.json, test/t8n/t8n.cpp
- Execute system contracts (Beacon roots system contract in Cancun) before executing any transaction. Fixes #822, fixes #832.
- Create output directory `--output.basedir` if it doesn't exist.
- Add a CMake smoke test for `evmone-t8n`. Fixes #813.
=> t8n: System contracts execution and other improvements

test/integration/t8n/CMakeLists.txt, test/integration/t8n/cancun_create_tx/txs.json, test/state/state.cpp, test/unittests/state_rlp_test.cpp
In case a transaction has a field with invalid value we still should RLP-encode it (instead of throwing an exception). This is legit usage in testing tools like evmone-t8n.
Also add an integration test for `evmone-t8n` based on real input.
Fixes #841.
=> RLP-encode invalid transactions

lib/evmone/advanced_instructions.cpp, lib/evmone/baseline_instruction_table.cpp, lib/evmone/eof.cpp, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/CMakeLists.txt, test/unittests/eof_validation_stack_test.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eip663_exchange_test.cpp, test/unittests/instructions_test.cpp, test/unittests/state_transition_eip663_test.cpp, test/utils/bytecode.hpp
Closes #774 
spec in https://eips.ethereum.org/EIPS/eip-663 and https://github.com/ipsilon/eof/blob/main/spec/eof.md
=> Implement EXCHANGE from EIP-663

lib/evmone/baseline.cpp
Use `std::make_unique_for_overwrite` to create padded code.
=> baseline: Refactor code padding

circle.yml
- execution-spec-tests: [v2.1.1](https://github.com/ethereum/execution-spec-tests/releases/tag/v2.1.1)
- ethereum/tests: [v13.2](https://github.com/ethereum/tests/releases/tag/v13.2)+fix
=> ci: Upgrade spec tests

circle.yml
Drop the Silkworm-driven execution of the blockchain tests. These tests don't provide any new coverage once we run state tests and some blockchain tests by evmone directly.
Moreover, maintaining a compatible Silkworm build while evmone is in development is challenging.
=> ci: Drop Silkworm-driven blockchain-tests job

codecov.yml
The `blockchaintests` flag is not used any more.
The `statetests` flag is unnecessarily limited to only some directories.
=> codecov: Drop flags config

test/unittests/precompiles_ripemd160_test.cpp
The test checks if the input length in bits value is properly stored in the final block in case the value is bigger than 2^32.
We remove the test because:
- it requires the input of size 0.5 GB which takes long time to process in debug builds; moreover, this is unrealistic memory size in EVM,
- our implementation doesn't split the value store into two uint32 stores, just use single uint64 store.
=> test: Drop the long-running RIPEMD160 unit test

test/bench/bench.cpp, test/integration/statetest/CMakeLists.txt, test/integration/statetest/tests1/SuiteA/test2_multi.json, test/statetest/statetest.cpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/unittests/statetest_loader_test.cpp
The ethereum/tests has a convention that there is a single test in a JSON file. However, execution-spec-tests don't follow this convention and put multiple tests in a single file.
This change loads and executes all tests from a JSON state test file.
Fixes https://github.com/ethereum/evmone/issues/862.
=> statetest: Run all tests from a JSON file

lib/evmone/advanced_instructions.cpp, lib/evmone/baseline_instruction_table.cpp, lib/evmone/eof.hpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/state/errors.hpp, test/state/host.cpp, test/state/host.hpp, test/state/state.cpp, test/state/state.hpp, test/statetest/statetest_loader.cpp, test/unittests/instructions_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition_eof_create_test.cpp, test/unittests/state_tx_test.cpp, test/utils/bytecode.hpp
Based on https://github.com/ethereum/evmone/pull/553
=> EOF: TXCREATE instruction

test/unittests/eof_validation_test.cpp
Recently on the EOF impl call we discussed a potential rule to validate and prohibit "weird" mixing of initcode-mode being on or off - during EOF validation.
We concluded we do not find such validation rule useful enough. In case this rule withstands the test of time, we should have a test case for this.
I think this is a test case where we acertain, that **none of the following conditions** are validated:
> - Each EOF subcontainer must either be referenced by an `EOFCREATE` or a `RETURNCONTRACT` instruction, but never both
> - Each EOF subcontainer may either contain `RETURNCONTRACT` or `RETURN` / `STOP` instructions, but never a mix of these two kinds
> - A subcontainer referenced by an `EOFCREATE` must never contain a `RETURN` / `STOP` instruction, whereas a subcontainer referenced by …
=> Test case: initcode-mode not being EOF-validated

lib/evmone/eof.cpp, test/unittests/eof_validation_test.cpp
- Validates the code by using a worklist of accessed code sections
- At the end if any code section was not accessed will return unreachable_code_sections error.
- Fixes tests previously containing unreachable code sections
=> Disallow code sections unreachable from section 0

lib/evmone/eof.cpp, test/unittests/eof_validation_test.cpp
Main part of the refactoring, that gets rid of recursion, is basically a transformation from:
- validate header
- for all subcontainers
- validate subcontainer (recursion)
- validate instructions
- validate jumps, stack etc.
to:
- validate header
- queue = { {container, header} }
- while queue not empty
- cont, header = queue.pop()
- for all subcontainers
- validate subcontainer header
- queue.push( {subcontainer, subcontainer_header} )
- validate instructions 
- validate jumps, stack etc.
=> EOF subcontainer validation without recursion

test/eofparse/eofparse.cpp, test/integration/CMakeLists.txt, test/integration/eofparse/CMakeLists.txt, test/integration/eofparse/two_errors.txt
In the evmone-eofparse tool exit with the number of invalid EOFs encountered.
Also add some basic integration tests.
Fixes #872
=> eofparse: Return number of errors

circle.yml
- Create separate job for `execution-spec-tests` (previously part of `state-tests`).
- Rename the `state-tests` to `ethereum-tests` to match the source of the tests (ethereum/tests).
- Publish coverage data with separate flags: `execution-spec-tests` and `ethereum-tests` respectively.
=> ci: Separate execution-spec-tests job

circle.yml, test/state/host.cpp
This implements [EIP-7610: Revert creation in case of non-empty storage](https://eips.ethereum.org/EIPS/eip-7610).
When a contract creation collides with an existing account it also reverts in case of the storage not being empty.
The ethereum/tests are upgraded to [v13.3](https://github.com/ethereum/tests/releases/tag/v13.3).
=> Implement EIP-7610 (non-empty storage create collision) and upgrade execution-tests

circle.yml
Use the official release v13.3 of ethereum/tests
(git tag also pushed to ipsilon/tests).
=> ci: Sync EOF tests with ethereum/tests

lib/evmone/instructions_calls.cpp, test/unittests/state_transition_eof_create_test.cpp
The special rule of handling EOF initcode in CREATE/CREATE2 instructions should not be activated before EOF is activated.
=> Fix EOF initcode handling before EOF is enabled

lib/evmone/advanced_analysis.hpp, lib/evmone/advanced_instructions.cpp, test/unittests/execution_state_test.cpp
This reuses some EVM stack utils from Baseline in Advanced. It should help with later modifications to the stack handling.
=> advanced: Use StackTop, drop Stack class

.clang-tidy
Since clang-tidy 17 the "Checks" can be specified as list of strings (instead of single string).
This should improve maintenance of the configuration: ability to leave comments about individual checks.
=> clang-tidy: Convert "Checks" to YAML list

lib/evmone/baseline.hpp, lib/evmone/eof.hpp, lib/evmone/execution_state.hpp, lib/evmone/tracing.hpp, test/state/rlp.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_eof_test.cpp, test/unittests/precompiles_ripemd160_test.cpp
This fixes builds with libc++ 18 where std::char_traits<unsigned char> is deprecated.
Requires https://github.com/ethereum/evmc/pull/712.
=> Upgrade EVMC and use evmc::{bytes, bytes_view}

test/blockchaintest/CMakeLists.txt, test/blockchaintest/blockchaintest.cpp, test/statetest/CMakeLists.txt, test/statetest/statetest.cpp, test/t8n/t8n.cpp
=> Add --version option to testing tools

test/unittests/evm_state_test.cpp
The `expected_hash` was unused.
=> test: Improve EXTCODEHASH test

lib/evmone/execution_state.hpp
Use `std::aligned_alloc()` (and `_aligned_malloc()` on MSVC) to allocate the memory for EVM stack.
This removes unnecessary initialization of the memory to zero (closes https://github.com/ethereum/evmone/issues/403).
The memory alignment is set to 32 bytes (as previously) but allows transitioning to "over-aligned" allocation for additional optimization
(see https://github.com/ethereum/evmone/issues/781).
=> StackSpace: use std::aligned_alloc()

circle.yml
Use CircleCI orb for codecov, use `_` in flag names because of the bug in the script (https://github.com/codecov/codecov-circleci-orb/issues/175).
=> CI: Update codecov upload

circle.yml
gcovr is easier to use and install on Debian. The branch information is also easily available, but we don't yet use it as there seems too much "false positives".
Coverage regression is due to some not executed files being included in the report. This is fine.
=> CI: Switch lcov to gcovr

lib/evmone/instructions_calls.cpp, test/unittests/state_transition_eof_calls_test.cpp
Delivers https://github.com/ipsilon/eof/pull/107 / https://github.com/ethereum/EIPs/pull/8535
=> Make EXT*CALL ASE-ready

lib/evmone/instructions.hpp, test/unittests/evm_eof_calls_test.cpp
Closes https://github.com/ethereum/evmone/issues/896, implements https://github.com/ipsilon/eof/pull/90 / https://github.com/ethereum/EIPs/pull/8617 the simplest way - by checking two first bytes of code on every instructions. 
A better version would be to store the result in ExecutionState, and the best to use an entirely different instruction table in `dispatch` functions.
Should we do the `ExecutionState` version right away now, or keep as is? Anyway, opening as draft until the EOF pr doesn't get merged (should be decided on the next eof impl call)
=> EOF RETURNDATA* to pad on OOB read

test/precompiles_bench/precompiles_bench.cpp, test/state/mpt.cpp
Fix clang-tidy check "readability-avoid-return-with-void-value". https://clang.llvm.org/extra/clang-tidy/checks/readability/avoid-return-with-void-value.html
=> tidy: Avoid returning void

test/state/precompiles.cpp, test/unittests/evm_calls_test.cpp
Fix clang-tidy check "void-nested-conditional-operator". https://clang.llvm.org/extra/clang-tidy/checks/readability/avoid-nested-conditional-operator.html
=> tidy: Avoid nested conditional operator

test/state/precompiles.cpp
The first 32 bytes of inputs to bn254's ecadd and ecmul precompiles are stored in a hash256 object but never used.
This fixes a copy&paste typo.
=> precompiles: Fix unused input hash in bn254

.clang-tidy, circle.yml, test/state/account.hpp, test/utils/utils.hpp
Upgrade compilers: GCC 14 and clang 18.
Alongside, tune clang-tidy config and fix small build warning/errors.
=> CI: Upgrade compilers: GCC 14 and clang 18

test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/CMakeLists.txt, test/state/mpt_hash.cpp, test/state/mpt_hash.hpp, test/state/state.hpp, test/state/test_state.cpp, test/state/test_state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_export.cpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/state_mpt_hash_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_call_test.cpp, test/unittests/state_transition_eof_calls_test.cpp, test/unittests/state_transition_tx_test.cpp, test/unittests/statetest_loader_test.cpp
This decouples the `state::State` for transaction execution from the state object for test definitions and asserts.
The `state::State` (also called "intra state") has some constructs and data related to transaction execution only (like "current" and "original" storage values). These should not be exposed to tests and make test definitions more complicated.
This separation should also help with adding new public API for EVM with transaction-level execution granularity.
=> test: Introduce TestState and TestAccount

circle.yml, lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/instructions_calls.cpp, test/state/host.cpp, test/unittests/eof_validation.cpp, test/unittests/eof_validation_test.cpp
This change only affects what is allowed in tests. Truncated data sections are not allowed at top level now, to check truncated data rules, tests should put it into subcontainers.
=> Disallow truncated data in toplevel containers

circle.yml, test/unittests/CMakeLists.txt
When running unit tests via ctest -j the profile data files seems to be overwritten by execution processes and the coverage information is incomplete. Set the LLVM_PROFILE_FILE environment variable for CTest registered unit tests and order the process number be a part of the profile file name.
=> test: Dump LLVM profile data to separate files

circle.yml
Seems to work barring https://github.com/ethereum/execution-spec-tests/pull/613 is not yet released (hence also not sure if coverage correctly treated yet)
=> Include execution-spec-tests in CI

test/integration/t8n/cancun_create_tx/txs.json, test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_tx_test.cpp
Fixes https://github.com/ethereum/evmone/issues/923.
=> test: Allow `"to": null` in JSON transaction

circle.yml, lib/evmone/baseline.cpp, lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_calls.cpp, test/eofparse/eofparse.cpp, test/eofparsefuzz/eofparsefuzz.cpp, test/eoftest/eoftest_runner.cpp, test/state/host.cpp, test/statetest/statetest_loader.cpp, test/unittests/eof_test.cpp, test/unittests/eof_validation.cpp, test/unittests/eof_validation.hpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_function_test.cpp, test/unittests/evm_eof_test.cpp, test/unittests/evm_fixture.hpp, test/unittests/state_transition_eof_create_test.cpp
Implementing https://github.com/ipsilon/eof/pull/86
Depends on #888 
TODO:
*if subcontainer is unreferenced, you cannot call its validation requiring neither runtime nor initcode mode.
=> EOF validation of subcontainer kinds

circle.yml, lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/unittests/eof_validation.cpp, test/unittests/eof_validation_test.cpp
https://github.com/ipsilon/eof/pull/125 / https://github.com/ethereum/EIPs/pull/8670
=> EOF: limit validated container size to MAX_INITCODE_SIZE

circle.yml
This can be done quite granularly, so maybe better this way. If approved, I'll add an issue to our board to not forget unsilence this test
=> Silence failing EOF EEST test

test/eoftest/eoftest_runner.cpp, test/unittests/eof_validation.cpp
This is the fixture format agreed on EOF implementers call and produced by EEST in https://github.com/ethereum/execution-spec-tests/pull/651
Based on #916 because it removes the tests for `initcode_runtime` container kind, and those were failing the run of exported validation tests.
=> EOF validation tests runner: support initcode flag

lib/evmone/CMakeLists.txt, lib/evmone/constants.hpp, lib/evmone/eof.cpp, test/state/host.cpp, test/state/host.hpp, test/state/state.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_test.cpp
Extract the `MAX_CODE_SIZE` and `MAX_INITCODE_SIZE` constants into common header.
=> Extract `MAX_CODE_SIZE` constant

test/eoftest/eoftest_runner.cpp, test/unittests/eof_validation.cpp
Add support for `"containerKind"` in the EOF validation JSON tests.
Specified in https://github.com/ethereum/execution-spec-tests/pull/651.
=> eoftest: Add support for "containerKind"

test/state/precompiles.cpp
Replace the fixed-size on-stack temporary buffer for precompiles with a heap-allocated buffer big enough to handle properly any precompile invocation.
This actually keeps the number of allocations the same. Previously the contents of the on-stack buffer were copied to heap by the Result constructor. Now we are creating the heap buffer in the first place and pass the ownership of it to the Result.
This fixes out-of-bounds memory accesses often being found by fuzzers.
=> precompiles: Improve output buffer handling

test/state/mpt.cpp, test/state/mpt.hpp, test/state/mpt_hash.hpp, test/unittests/state_mpt_hash_test.cpp, test/unittests/state_mpt_test.cpp, test/unittests/state_rlp_test.cpp
And move it from mpt.hpp to mpt_hash.hpp.
=> test: Rename `emptyMPTHash` → `EMPTY_MPT_HASH`

test/blockchaintest/blockchaintest_runner.cpp
Do not execute system contracts on the blockchain test genesis block. It is unspecified how they should behave and the genesis block is expected to be a static block without transactions.
Instead just validate there are no transactions/receipt/withdrowals referenced by the genesis block header.
=> blockchaintest: Simplify genesis handling

lib/evmone/eof.cpp, test/unittests/eof_validation.cpp
Fixes the bug introduced in https://github.com/ethereum/evmone/pull/947 where reading the version byte is missing the bounds check.
This bug is hard to detect when `std::string` is used as the test container. Found by a fuzzer.
=> Fix parsing EOF version in header

test/unittests/eof_validation.cpp
In EOF validation tests, move the container to new heap-allocated buffer of exact size to easily find out-of-buffer reads with address sanitizer.
=> test: Improve out-of-buffer detection in EOF tests

test/state/host.cpp, test/state/host.hpp, test/unittests/state_transition_eof_create_test.cpp
The two implementations did the exact same thing (maybe they diverged earlier?). At this point it makes sense to have one.
=> eof: Merge implementations of `compute_[create2|eofcreate]_address`

lib/evmone/baseline_execution.cpp, test/integration/CMakeLists.txt
Depends on https://github.com/ethereum/evmc/pull/713, needs to set the submodule to a `master` revision of evmc before merging
Before, running `evmc run` with validate_eof would not recognize creation txs (which have to be validated as initcode) and regular calls to a deployed contract (which have to be validated as runtime) correctly. This fixes that.
Validation is only done on the top-level frame (`msg->depth == 0`), to avoid re-doing it on every deeper frame (all subcontainers are validated recursively anyway, so all code supplied will be validated).
Initcode/runtime code kind is decided by the `msg->kind`, which handling is in turn fixed in the `evmc run` in https://github.com/ethereum/evmc/pull/713
=> Fix `validate_eof` flag for EOF creation txs

circle.yml
Switch to the updated `eof-toplevel` branch of ipsilon/tests.
After rebasing the number of changes is smaller than it was.
The ethereum/tests PR: https://github.com/ethereum/tests/pull/1381.
Also run the EOF tests from upstream ethereum/tests v14.0
with longer exclusion list.
=> ci: Update ethereum/tests EOF tests

circle.yml
Drop build and support for MSVC 32-bit x86 architecture. "This platform is almost extinct".
We continue to have some other 32-bit builds (GCC x86 and riscv32) to check pointer size and `size_t` correctness.
=> ci: Drop MSVC 32-bit support

lib/evmone/eof.cpp, test/unittests/eof_validation_test.cpp
Credit to @chfast to find the case via fuzzing, as well as suggest this version of the fix (alternative version in comment, not sure which is cleaner anymore)
=> eof: fix multi-container-section case

circle.yml
Upgrade ethereum/tests to the recent commit of the develop branch. This allows using the same revision for legacy and EOF tests and drop the ipsilon fork.
The changes since the v14.0 release is removal of EEST migrated tests and small EOF validation updates.
=> ci: Upgrade ethereum/tests

cmake/blst.cmake, lib/evmone_precompiles/CMakeLists.txt
Configure blst dependency using CMake's ExternalProject. 
This has been tested here (https://github.com/ethereum/evmone/pull/979) and in Silkworm (https://github.com/erigontech/silkworm/pull/2245).
=> precompiles: Prepare blst dependency 

circle.yml
EOF tests have been updated so no failures are expected.
=> ci: Upgrade ethereum/tests to v14.1

test/unittests/evmmax_bn254_add_test.cpp, test/unittests/evmmax_bn254_mul_test.cpp, test/unittests/evmmax_secp256k1_test.cpp
=> test: Remove unused evmmax::ModArith variables

cmake/blst.cmake
Pass the same C compiler which CMake is using to the blst build script and make sure the compiler's required flags (e.g. `-isysroot` is also included. Previously we relied on the script to find a C compiler on its own, but this might have not worked.
=> cmake: Improve blst build on macOS

test/blockchaintest/blockchaintest_runner.cpp, test/state/CMakeLists.txt, test/state/state.cpp, test/state/state.hpp, test/state/system_contracts.cpp, test/state/system_contracts.hpp, test/t8n/t8n.cpp, test/unittests/state_system_call_test.cpp
Refactor and abstract the `system_call()` to make adding new system contracts easier.
=> Refactor `system_call()`

lib/evmone/execution_state.hpp, test/unittests/execution_state_test.cpp
Use `std::unique_ptr` to manage realloc/free allocated EVM memory buffer in `Memory`. This makes `Memory` and `ExecutionState` types movable.
=> Make ExecutionState's Memory movable type

test/state/precompiles.cpp, test/state/precompiles.hpp, test/state/precompiles_internal.hpp, test/unittests/state_precompiles_test.cpp
Preparation to implementation of  [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537): "Precompile for BLS12-381 curve operations".
=> precompiles: Add BLS precompiles IDs

cmake/Hunter/config.cmake, lib/evmone_precompiles/ecc.hpp, test/unittests/evm_eip7516_blobbasefee_test.cpp, test/unittests/evmmax_bn254_add_test.cpp, test/unittests/evmmax_bn254_mul_test.cpp, test/unittests/evmmax_test.cpp, test/unittests/state_block_test.cpp, test/unittests/state_mpt_hash_test.cpp, test/unittests/state_mpt_test.cpp, test/unittests/statetest_loader_tx_test.cpp, test/unittests/tracing_test.cpp
This version has `_u384` literal suffix
and `using namespace intx::literals` as an alternative to `using namespace intx`.
=> cmake: Upgrade intx to v0.12.0

circle.yml, lib/evmone_precompiles/CMakeLists.txt, lib/evmone_precompiles/bls.cpp, lib/evmone_precompiles/bls.hpp, test/state/precompiles.cpp, test/unittests/CMakeLists.txt, test/unittests/precompiles_bls_test.cpp
Implementation of the `bls12_g1add` precompile: E1 affine points' addition from BLS12-381 curve according to the EIP-2537 spec https://eips.ethereum.org/EIPS/eip-2537#abi-for-g1-addition.
Depends on https://github.com/ethereum/evmone/pull/984
=> precompiles: Implement EIP-2537's `bls12_g1add`

circle.yml, test/state/system_contracts.cpp, test/state/system_contracts.hpp, test/unittests/state_system_call_test.cpp, test/utils/utils.cpp
Implement [EIP-2935](https://eips.ethereum.org/EIPS/eip-2935) "Serve historical block hashes from state" required for the [Prague](https://eips.ethereum.org/EIPS/eip-7600) revision.
This mostly adds new system contract.
=> EIP-2935: Serve historical block hashes from state

circle.yml
Upgrade the EEST tests for Prague packaged by the Pectra devnet-3 spec to version v1.5.0.
=> ci: Upgrade EEST pectra-devnet-3 to v1.5.0

test/statetest/statetest_export.cpp, test/statetest/statetest_loader.cpp, test/unittests/state_transition.cpp
I was wrong when I said that the format inconsistency had a test which we can make pass by amending the exported format - there were no exclusions which my fix would fix. So to have some testing mechanism of correctness, we can maybe add an assertion in `statetest_loader` like this? I don't want to overdo it and this seems safe to do.
I guess we can also leave it without the assertion.
I don't know yet about the other format inconsistencies found, so I might add more commits here
=> test: Ensure exported state tests have all fields

circle.yml, lib/evmone_precompiles/bls.cpp, lib/evmone_precompiles/bls.hpp, test/state/precompiles.cpp, test/unittests/precompiles_bls_test.cpp
Implementation of the `bls12_g1mul` precompile: E1 affine point's multiplication from BLS12-381 curve by a scalar according to the EIP-2537 spec https://eips.ethereum.org/EIPS/eip-2537#abi-for-g1-multiplication.
Depends on https://github.com/ethereum/evmone/pull/982
=> precompiles: Implement EIP-2537's `bls12_g1mul`

lib/evmone/baseline.hpp, lib/evmone/baseline_execution.cpp, lib/evmone/vm.cpp, lib/evmone/vm.hpp, test/bench/helpers.hpp
This adds an array of `ExecutionState` objects to the `VM` instance. They are used internally in the Baseline interpreter instead of passing one via API. This removes the need of maintaining object pool for execution states. 
However, this also makes the `VM` non-thread safe, but it is fine for current users. We can improve on this in the future by spiting the the VM into two parts: non-thread safe opaque execution context and a thread-safe VM with user configuration.
=> baseline: VM-level execution states

test/t8n/t8n.cpp
Pulled out of #961 
This is related to https://eips.ethereum.org/EIPS/eip-7685 and required for filling EEST for Prague.
=> Add requestsRoot to t8n output for Prague

circle.yml, lib/evmone_precompiles/bls.cpp, lib/evmone_precompiles/bls.hpp, test/state/precompiles.cpp, test/unittests/precompiles_bls_test.cpp
Implementation of the `bls12_map_fp_to_g1` and `bls12_map_fp2_to_g2` precompiles: mapping of `fp` field element to a point on `E1` curve (BLS12-381) and mapping `fp2` extension field element to a point on `E2` curve (BLS12-381) according to the EIP-2537 spec https://eips.ethereum.org/EIPS/eip-2537#abi-for-mapping-fp-element-to-g1-point and https://eips.ethereum.org/EIPS/eip-2537#abi-for-mapping-fp2-element-to-g2-point.
Depends on: https://github.com/ethereum/evmone/pull/1010
=> precompilles: Implement mapping of field elements to `BLS12-381` curve points

test/state/host.cpp, test/state/state.cpp
This is required for [EIP-7702 implementation](https://github.com/ethereum/evmone/pull/961), because there the sender's nonce must be bumped before processing transaction's Authorization List.
=> Increment transaction sender's nonce before entering execution frame

test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_test.cpp, test/unittests/statetest_loader_tx_test.cpp
Also set default `chain_id` to 1 - see confirmation that this is expected behavior https://discord.com/channels/595666850260713488/753271902520213625/1280839101687533619
Pulled out of #961, required for 7702 tests.
=> test: Support chain_id in loading multi-transaction state tests

test/blockchaintest/blockchaintest_runner.cpp, test/state/test_state.cpp, test/state/test_state.hpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/state_system_call_test.cpp, test/unittests/state_transition.cpp
Wrap the usage of the state transition API from the `evmone::state` for tests so that the new API in `evmone::test` only exposes `TestState` and hides `state::State`.
This isolates usage of the `evmone::state` to lower the disturbance caused by API modifications,
e.g. in https://github.com/ethereum/evmone/pull/802.
=> test: Wrap usage of state transition API

test/state/state.cpp, test/state/state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_export.cpp, test/unittests/state_transition.cpp
Moves the function `get_invalid_tx_message()` function from `evmone::state` (state.cpp) to `evmone::test` (statetest_export.cpp).
=> test: Move invalid tx messages to state utils

test/blockchaintest/blockchaintest.hpp, test/state/CMakeLists.txt, test/state/block.cpp, test/state/block.hpp, test/state/bloom_filter.cpp, test/state/host.hpp, test/state/mpt_hash.cpp, test/state/state.cpp, test/state/state.hpp, test/state/system_contracts.cpp, test/state/transaction.cpp, test/state/transaction.hpp, test/statetest/statetest.hpp
We are going to hide the `State` in state.hpp from public. This change moves other types out of this file make the future transition easier to control.
The git history is preserved by using file renames and a lot of merge commits (octopus merge didn't work for me).
=> state: Split transaction and block related types of out state.hpp

.clang-tidy
We discussed that this check is too strict because we want to put `[[nodiscard]]` only in very specific places where ignoring a returned value is close to logic error. The clang-tidy check asking to put it on every class getter is too much.
=> clang-tidy: Disable modernize-use-nodiscard

lib/evmone/eof.cpp, lib/evmone/eof.hpp, test/state/host.cpp, test/unittests/eof_test.cpp
Replace runtime evaluated `keccak256("EF00")` with a constant returned for an account with EOF code.
=> eof: Return constant hash of EXTCODEHASH of EOF

lib/evmone/eof.cpp
Optimize `validate_instructions()` by using `std::move` on arguments to returned `InstructionValidationResult`.
=> eof: Optimize EOF validation by using `std::move`

.clang-tidy
It may be intentional to do `&v[0]` instead of `v.data()` as a way of saying "give me the address of the 0th element" instead of "give me the address of the array of elements".
An example: https://github.com/ethereum/evmone/pull/1046.
=> clang-tidy: Disable readability-container-data-pointer

test/state/system_contracts.cpp
Don't use the reference type bytes_view as the return type of system contracts' `get_input()`. This works now because return references to objects owned by `BlockInfo` but will likely become a footgun when an API boundary is introduced (e.g. `BlockInfo::get_block_hash()`).
=> state: Avoid returning bytes_view in system contracts

lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/instructions.hpp, test/unittests/eof_test.cpp
Introduces `EOF1Header::get_type` function to read individual EOF
code types. This is fast procedure because we need to read at most 4
bytes and a know offset. By doing so we avoid allocating separated
vector to types.
Closes https://github.com/ethereum/evmone/issues/1003.
=> Optimize EOF by reading types on demand

lib/evmone/eof.cpp
This allows separate header and type validation and simplify the implementation of the former.
=> eof: Move type validation outside of header validation

test/state/errors.hpp, test/state/state.cpp
This is awaiting updates in EEST.
=> EIP-7702: Change transaction validity rules according to latest spec

test/unittests/eof_validation_stack_test.cpp, test/unittests/eof_validation_test.cpp
- [backwards_rjump_variable_stack_0](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_stack_test.cpp#L108)
- Repeated in [self_referencing_jumps_variable_stack](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_stack_test.cpp#L840)
- [forwards_rjump_0](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_stack_test.cpp#L154)
- Repeated in [EOF1_valid_rjump](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_test.cpp#L392)
- [backwards_rjumpi_0](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_stack_test.cpp#L222)
- Repeated in [EOF1_valid_rjumpi](https://github.com/ethereum/evmone/blob/master/test/unittests/eof_validation_test.cpp#L415-L417)
- …
=> Remove repeated unit tests

test/state/host.cpp, test/unittests/state_new_account_address_test.cpp
Remove Host's dependency on RLP library by re-implementing `compute_create_address()`.
Closes https://github.com/ethereum/evmone/issues/783.
=> state: Implement `CREATE` address without RLP lib

test/state/block.hpp, test/state/host.cpp, test/state/host.hpp, test/state/state.cpp, test/state/state.hpp, test/state/state_view.hpp, test/state/system_contracts.cpp, test/state/system_contracts.hpp, test/state/test_state.cpp, test/state/test_state.hpp
Define interface `BlockHashes` to access hashes of known block headers. This substitutes the usage of `BlockInfo::known_block_hashes` which can only work in tests, but not in production code.
The method `get_block_hash()` could have been added to `StateView`, but I decided keep it separated for now.
=> Introduce `BlockHashes` interface

test/blockchaintest/blockchaintest_runner.cpp, test/state/block.hpp, test/state/test_state.cpp, test/state/test_state.hpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/state_system_call_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition.hpp, test/unittests/state_transition_block_test.cpp, test/unittests/statetest_loader_block_info_test.cpp
This removes `.known_block_hashes` from `state::BlockInfo`. Block hashes in tests are now provided by `TestBlockHashes`.
The main goal here is to remove test-only fields from `state::BlockInfo`.
=> test: Split know block hashes into TestBlockHashes

lib/evmone/vm.hpp, test/unittests/tracing_test.cpp
Add `VM::remove_tracers()` method to remove all registered tracers.
=> vm: Allow for tracers removal

test/bench/CMakeLists.txt
We are executing all available benchmarks to detect problems in tools and benchmark inputs. Use newer options --benchmark_min_time=1x to execute each benchmark exactly once.
=> test: Use newer --benchmark_min_time=1x

test/state/state.cpp, test/state/state.hpp, test/state/test_state.cpp, test/unittests/state_tx_test.cpp
This change separates transaction validation in
`state::validate_transaction()` from `state::transition()` which previously was also validating the transaction.
Readability goes up in cost of slightly lower efficiency. The change is also good for API because transaction validation usually happens in different place than execution.
=> state: Separate transaction validation from transition

test/statetest/statetest_loader.cpp
EEST don't use labels so exclude the code parsing labels from coverage by using gcov markers in comments.
=> test: Exclude parsing input labels from coverage

test/state/host.cpp
In the Host inspect the code address and skip execution if the code is empty.
This help with Silkworm performance because there are a lot of ETH transfers between EOAs.
=> host: Skip execution of empty code

circle.yml, test/blockchaintest/blockchaintest_runner.cpp, test/state/requests.cpp, test/state/requests.hpp, test/t8n/t8n.cpp
https://eips.ethereum.org/EIPS/eip-6110
=> EIP-6110: Supply validator deposits on chain

cmake/Hunter/init.cmake
as title, I was getting this:
https://app.circleci.com/pipelines/github/ethereum/evmone/7895/workflows/db9b6ae2-d982-4eb4-8e27-59aa86705862/jobs/121408
without.
```
**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.12.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
/c/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake
-- [cable ] Cable 0.5.0 initialized
-- Build type: Release
-- [hunter] Initializing Hunter workspace (0dfbc2cb5c4cf7e83533733bdfd2125ff96680cb)
-- [hunter]   https://github.com/cpp-pm/hunter/archive/v0.25.3.tar.gz
-- [hunter]   -> …
```
=> build: Bump hunter to v0.25.8

circle.yml, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/statetest/statetest_loader.cpp
I took the liberty to coarsely disable 4844 (and 4788) blockchain tests across the board, as they will be re-enabled in #1077, which needs to be rebased on top of these changes (invalid block blockchain tests handling in that branch is currently not complete!).
Before merging I'll squash the 1st and last commits together, they aim at the same thing.
Note, that a next step would be to respect the `expectException` field from the test and only accept specific reasons for block invalidity. For now I only handle valid-invalid.
=> tests: Enable invalid block blockchain tests

test/state/requests.cpp, test/state/requests.hpp, test/state/system_contracts.cpp, test/t8n/t8n.cpp, test/unittests/state_system_call_test.cpp
Change Requests representation to byte array of type + requests data.
Closes #1086
=> Get rid of extra requests data copying when calculating requests hash

test/state/state.cpp, test/state/transaction.hpp, test/statetest/statetest_loader.cpp
Intruduce new transaction type 4 "set code" from EIP-7702. This allows
us to recognize such transaction in tests prior full implementation.
=> Introduce "set code" (4) transaction type for EIP-7702

test/bench/synthetic_benchmarks.cpp
Use C++20 ability to generate all comparison operators for the `CodeParams` benchmarking utility class.
=> test: Generate default comparison operator for CodeParams

lib/evmone/baseline_analysis.cpp, lib/evmone/eof.cpp, test/bench/bench.cpp, test/blockchaintest/blockchaintest.cpp, test/eoftest/eoftest.cpp, test/state/bloom_filter.cpp, test/statetest/statetest.cpp, test/unittests/state_transition.cpp
Apply suggestions by the clang-tidy's modernize-use-ranges check.
=> tidy: Use ranges version of C++ algorithms

lib/evmone/advanced_analysis.cpp, lib/evmone_precompiles/sha256.cpp, test/statetest/statetest_loader.cpp, test/unittests/precompiles_ripemd160_test.cpp, test/unittests/state_rlp_test.cpp
This sets the internal linkage of functions which should have it. `inline` nor `constexpr` functions don't have internal linkage so use `static` or put them in the anonymous namespace. 
These issues are found with clang-tidy's misc-use-internal-linkage.
=> tidy: Properly set internal linkage to internal functions

circle.yml
Run EEST tests pectra-devnet-5@v1.2.0 alongside the devnet-4 tests. This allows migrating to the devnet-5 specs EIP-by-EIP. In this PR we just enable example devnet-5 tests which happen to pass in the devnet-4 implementation.
=> ci: Add pectra-devnet-5 EEST

circle.yml
Otherwise some tests deleted from devnet-4 remain when testing devnet-5.
=> ci: Clean directory before downloading execution spec tests

circle.yml, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/block.cpp, test/state/block.hpp, test/state/host.cpp, test/state/state.cpp, test/state/transaction.hpp, test/statetest/statetest_loader.cpp, test/t8n/t8n.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/state_transition_tx_test.cpp, test/unittests/state_tx_test.cpp
```
build/bin/evmone-blockchaintest ~/Downloads/fixtures_test_prague_devnet_5/blockchain_tests/cancun/eip4844_blobs/
...
[==========] 43 tests from 7 test suites ran. (4250 ms total)
[  PASSED  ] 43 tests.
```
:green_apple: 
~~NOTE: I'll squash the commits before merging.~~
~~NOTE2: opening as draft to work through CI issues. Not reviewable yet, but if I'm completely off the scent somewhere, please let know~~
Ready for review
=> EIP-4844 - pass blockchain tests

test/state/state.cpp
- Compute transaction data cost using "token" count from EIP-7623.
- Clean up related constants.
- Treat creation as additional cost (`TX_CREATE_COST`).
=> Refactor transaction intrinsic gas calculation

circle.yml, test/state/state.cpp, test/state/transaction.hpp, test/statetest/statetest_runner.cpp, test/unittests/state_transition_tx_test.cpp, test/unittests/state_tx_test.cpp
This implements [EIP-7623](https://eips.ethereum.org/EIPS/eip-7623).
In effect, during transaction validation we compute minimal transaction
gas cost. After transaction execution the amount of gas used is
increased to this value if lower.
~~Requires #1107 #1108~~. Merged
=> Implement EIP-7623 "Increase calldata cost"

circle.yml, test/state/precompiles.cpp, test/state/precompiles.hpp, test/state/precompiles_internal.hpp, test/unittests/state_precompiles_test.cpp
Apply recent [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) spec updates:
- update gas costs:
- https://github.com/ethereum/EIPs/pull/9097
- https://github.com/ethereum/EIPs/pull/9098
- https://github.com/ethereum/EIPs/pull/9116
- remove redundant MUL precompiles:
- https://github.com/ethereum/EIPs/pull/8945
=> Updates to BLS precompiles (EIP-2537)

circle.yml, test/state/system_contracts.hpp
The [pectra-devnet-5 specs] includes an [update to EIP-2935]'s system contract and its address.
To pass blockchain tests the https://github.com/ethereum/evmone/pull/1094 is required, but we are going to merge this change first.
[pectra-devnet-5 specs]: https://notes.ethereum.org/@ethpandaops/pectra-devnet-5
[update to EIP-2935]: https://github.com/ethereum/EIPs/pull/9144
=> Update Blockhash History system contract address (EIP-2935)

circle.yml, test/integration/t8n/CMakeLists.txt, test/state/requests.cpp, test/t8n/t8n.cpp
Apply the [EIP-7685 update] included in [pectra-devnet-5].
[EIP-7685 update]: https://github.com/ethereum/EIPs/pull/8989
[pectra-devnet-5]: https://notes.ethereum.org/@ethpandaops/pectra-devnet-5
This requires a fix in tests for calldata repricing logic according to https://github.com/ethereum/EIPs/pull/9227
=> Exclude empty requests data in commitment (EIP-7685)

test/integration/statetest/CMakeLists.txt, test/integration/statetest/filter/one_failing_of_two.json, test/statetest/statetest.cpp
This PR improves state test functionality by allowing filtering by test case name defined inside json test file.
=> tests: Add option to filter state tests by name

circle.yml, test/state/system_contracts.hpp
- [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002) update: https://github.com/ethereum/EIPs/pull/9119.
- [EIP-7251](https://eips.ethereum.org/EIPS/eip-7251) update: https://github.com/ethereum/EIPs/pull/9127
=> Update system contract addresses according to latest spec

circle.yml, cmake/toolchains/clang-libcxx-debug.cmake
For the sanitizer build use libc++ with debug hardening enabled.
Closes https://github.com/ethereum/evmone/issues/906.
=> ci: Build clang/sanitizers with debug libc++

test/state/account.hpp, test/state/host.cpp, test/state/state.cpp, test/state/state_diff.hpp, test/state/test_state.cpp
Use `std::optional` to indicate that an account's code has changed in the state diff.
=> state: Simplify code modification indicator in StateDiff

circle.yml, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/block.cpp, test/state/block.hpp, test/statetest/statetest.hpp, test/statetest/statetest_loader.cpp, test/statetest/statetest_runner.cpp, test/t8n/t8n.cpp, test/unittests/state_block_test.cpp, test/unittests/state_transition.cpp, test/unittests/state_transition_block_test.cpp, test/unittests/state_tx_test.cpp, test/unittests/statetest_loader_block_info_test.cpp, test/unittests/statetest_loader_test.cpp
Implements [EIP-7691](https://eips.ethereum.org/EIPS/eip-7691). It seems only 7702 is missing (once spec stabilizes) from passing EEST devnet-5/6 tests
The parametrization of blob gas schedule with `rev` led to quite a bit of fallout...
=>  Support EIP-7691: Blob throughput increase

lib/evmone/baseline_execution.cpp
Refactor the baseline interpreter by taking the beggining of the code once. This also workarounds a clang-tidy warning about .data() usage.
=> baseline: Get code begin once

.clang-tidy, lib/evmone/advanced_instructions.cpp, lib/evmone/eof.cpp, lib/evmone/instructions_calls.cpp, test/state/host.cpp, test/state/precompiles.cpp, test/state/state.cpp, test/unittests/evm_test.cpp, test/unittests/instructions_test.cpp
This brings the configuration to the clang-tidy-20 compatibility.
=> Update clang-tidy config and suppress some warnings

lib/evmone/eof.cpp
The check that type section size matches the number of code sections is done twice in EOF validation:
- in `validate_section_headers()`
- in `validate_header()` which always calls `validate_section_headers()` so this check never fails.
I decided to leave the check in `validate_header()` because it better fits there.
=> eof: Remove duplicated type section size check

lib/evmone/eof.cpp
The stack height check for the next instruction is always successful. Downgrade the check of the result of the `visit_successor` in this case to assert.
=> eof: Cleanup stack height validation for next instruction

lib/evmone_precompiles/bls.cpp, test/unittests/precompiles_bls_test.cpp
It has been identified that the BN254 pairing check precompile has a bug in the implementation in how it handles points-at-infinity. The correct behavior is to "ignore" the pairs with at least one point-at-infiity, but not to always return 1 in this case.
The bug likely is the result of the mis-interpretation of the ambiguous note in the spec, remove it https://github.com/ethereum/EIPs/pull/9424.
=> precompiles: Fix BN254 pairing check

lib/evmone_precompiles/bls.cpp
Pre-computing the lines for the Miller loop in the BLS pairing check don't improve performance because the lines are used only once.
=> Drop lines precomputation in BLS pairinig check

cmake/cable/README.md
Noticed that the `git-subtree` documentation link in `README.md` was pointing to an outdated `.txt` file. The Git repo has been using `.adoc` for that part of the docs for a while now, so I’ve updated the URL to the correct one.
[git/git@561de07](https://github.com/git/git/commit/561de07b57fcc2057fb6b96043f008a5b83f140c) — shows the replacement of `git-subtree.txt` with `git-subtree.adoc` in Git’s documentation.
=> docs: 404 link in `cmake/cable/README.md`

test/state/requests.cpp, test/state/requests.hpp, test/unittests/state_deposit_requests_test.cpp
Turns out on Sepolia deposit contract is different and can emit other logs (ERC20's `Transfer`)
=> Check for topic when parsing deposit contract logs

lib/evmone/advanced_instructions.cpp, lib/evmone/eof.cpp, lib/evmone/eof.hpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/eof_example_test.cpp, test/unittests/eof_validation_test.cpp, test/unittests/evm_eof_test.cpp, test/unittests/instructions_test.cpp, test/unittests/state_transition_eof_create_test.cpp, test/utils/bytecode.hpp
As title, proposed for eof-devent-1, aligns with https://github.com/ipsilon/eof/pull/182. ~~Requires an update~~ Doesn't really require an update to EEST, but accompanying change drafted in https://github.com/ethereum/execution-spec-tests/pull/1284
=> eof: Rename RETURNCONTRACT to RETURNCODE

test/state/precompiles.cpp
Get rid of silkpre overwrite for precompiles implementations because we are only using it for expmod. Call `silkpre_expmod_execute()` directly from `expmod_execute()` as a better fallback than `expmod_stub()`.
=> precompiles: Call silkpre directly from expmod_execute()

test/statetest/statetest_loader.cpp, test/unittests/state_transition_create_test.cpp, test/unittests/statetest_loader_test.cpp
Idea originated in https://github.com/ethereum/evmone/pull/961#pullrequestreview-2606700539
=> Add prestate validation checks to state test loader

include/evmmax/evmmax.hpp, test/unittests/evmmax_test.cpp
Add method for computing modular inversion using extended binary Euclidean algorithm. This algorithm, even in a simple form, is significantly faster (~5x) than computing the inversion as pow(x, p-2, p) by using a dedicated addchain of MULs.
=> evmmax: Add inversion method

lib/evmone_precompiles/bn254.cpp, lib/evmone_precompiles/bn254.hpp, lib/evmone_precompiles/ecc.hpp
This makes the BN254 `ecadd` precompile 30% faster.
=> precompiles: Use classic EC point add formula

lib/evmone_precompiles/ecc.hpp
Simplify and optimize the procedure for EC point multiplication. This reduced EC point multiplication time by 30%.
```
Comparing o/ec to o/ec-mulopt
Benchmark                                                                  Time             CPU      Time Old      Time New       CPU Old       CPU New
-------------------------------------------------------------------------------------------------------------------------------------------------------
precompile<PrecompileId::ecrecover, evmmax_cpp>_mean                    -0.2961         -0.2960        312197        219765        312126        219741
precompile<PrecompileId::ecmul, evmmax_cpp>_mean                        -0.3179         -0.3180        144903         98842        144882         98814
```
=> precompiles: Optimize EC point multiplication

test/state/precompiles.cpp
Refactor the loop preparing inputs for the BN254 pairing check.
=> precompiles: Refactor BN254 ecpairing

lib/evmone/instructions_calls.cpp, test/unittests/eof_example_test.cpp, test/utils/bytecode.hpp
Update with https://github.com/ipsilon/eof/pull/156, planned for EOF Osaka-devnet-1. EOFCREATE stack args order to match that of EXT*CALL.
The change in EEST which goes in hand with this: https://github.com/ethereum/execution-spec-tests/pull/1274
=> eof: Align EOFCREATE args with EXT*CALL

lib/evmone_precompiles/bn254.cpp, lib/evmone_precompiles/ecc.hpp, lib/evmone_precompiles/secp256k1.cpp
=> precompiles: Add EC mixed-add formula

docs/efficient_gas_calculation_algorithm.md
Before: "This is difference of the stack height before and after the instruction"
After: "This is the difference in stack height before and after the instruction"
The original phrase was grammatically incorrect. "Difference in" is the proper way to describe changes in quantity.
Improved readability of the 'Undefined Instructions' section:
Before: "Undefined instructions have base gas cost 0 and not stack requirements."
After: "Undefined instructions have a base gas cost of 0 and no stack requirements."
Added "of" for clarity and changed "not stack requirements" to "no stack requirements" to make it sound more natural.
=> Grammar Fixes

circle.yml
As title. Current `master` should pass v4.3.0 tests being the eof-devnet-1 ones
=> ci: Upgrade EEST to v4.3.0 - EOF

test/state/system_contracts.cpp, test/unittests/state_system_call_test.cpp
When executing "requests" system contracts at the end of a block we create single-byte requests for the matching contract. I think this comes from the earlier spec revision. Currently this is not necessary because empty requests are skipped:
- when computing the requests hash: https://github.com/ethereum/evmone/blob/f9f8d5103c14bb0c4e6a3422884d1624adb1dda9/test/state/requests.cpp#L17
- in t8n: https://github.com/ethereum/evmone/blob/5a42fc60c4bdf471d115975c9858550ddc271f6b/test/t8n/t8n.cpp#L267
=> Don't create dummy requests for empty system contracts

test/state/system_contracts.cpp, test/state/system_contracts.hpp, test/state/test_state.cpp
Split execution for "storage" and "requests" system contract. The differences between executing these sets of system contracts are already big enough and are going to increase in the future.
=> Refactor system contracts execution

test/utils/utils.cpp
Add missing EVM revision transition schedules for blockchain tests:
- BerlinToLondonAt5
- ParisToShanghaiAt15k
Closes https://github.com/ethereum/evmone/issues/1210.
=> test: Add missing revision schedules

circle.yml, test/blockchaintest/blockchaintest_runner.cpp, test/state/requests.cpp, test/state/requests.hpp, test/state/system_contracts.cpp, test/state/system_contracts.hpp, test/state/test_state.cpp, test/state/test_state.hpp, test/t8n/t8n.cpp, test/unittests/state_deposit_requests_test.cpp, test/unittests/state_system_call_test.cpp
- The EIP-7002 (withdrawal requests) and EIP-7251 (consolidation requests) have been updated to specify that a failing system contract makes the block invalid.
- https://github.com/ethereum/EIPs/pull/9508
- https://github.com/ethereum/EIPs/pull/9582
- Add support for minimal EIP-6110 deposit log validation following the spec update. The invalid deposit logs invalidate the block.
- https://github.com/ethereum/EIPs/pull/9460
- Upgrade EEST to v4.3.0
=> Handle failing system contracts

lib/evmone/CMakeLists.txt, lib/evmone/lru_cache.hpp, test/internal_benchmarks/CMakeLists.txt, test/internal_benchmarks/lru_cache_bench.cpp, test/unittests/CMakeLists.txt, test/unittests/lru_cache_test.cpp
Adds generic single-threaded implementation of
the least recently used (LRU) cache.
This is to be used to cache the code and code analysis.
=> LRU cache utility

test/bench/bench.cpp, test/bench/synthetic_benchmarks.cpp
Refactor lambda usage to capture structured bindings (finally available in C++20) without declaring additional lambda capture variable. This also fixes clang-17 "declaration shadows a structured binding" warnings.
=> bench: Lambda capture structured bindings (C++20)

CMakeLists.txt, circle.yml
- Enable optimization in the clang's coverage build.
- Disable asserts in the clang's coverage build. Asserts are not good for coverage because they always have an uncovered branch.
- Generate better HTML report on CI.
- Extend coverage collection to all source code (not only libevmone).
Here is the HTML report for this PR: https://output.circle-artifacts.com/output/job/bd5443f4-1c3e-425b-a7ab-7fae838f229b/artifacts/0/coverage/html/coverage/home/builder/index.html.
=> build,ci: Improve clang's source based coverage

lib/evmone/advanced_analysis.hpp, lib/evmone/baseline_execution.cpp, lib/evmone/execution_state.hpp, lib/evmone/instructions.hpp
This is more correct C++ because it avoids the "bottom" pointer (one below the stack space base pointer). In C++ only pointers to the elements of an array and the "end" pointers are well defined.
This also potentially helps with the "overaligned" stack space optimization. To be continued...
=> Track EVM stack "end" instead of "top"

circle.yml, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/state/block.hpp
This adds support for multiple forks in one blockchain test, including finding the canonical fork based on total difficulty.
=> test: Suppport multichain blockchain tests

lib/evmone/instructions.hpp
This is guaranteed by the stack space allocation.
This allows the compiler to use aligned vector load instructions. Unfortunately, no performance gains on latest CPUs because aligned/unaligned instructions have the same cost there.
=> Mark the EVM stack pointer as 32-byte aligned

circle.yml, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/statetest/statetest_loader.cpp, test/unittests/blockchaintest_loader_test.cpp, test/unittests/statetest_loader_block_info_test.cpp
There are InvalidBlocks tests that check that Withdrawal's fields fit uint64.
Also note that the tests with fields wider than uint256 are being deleted: https://github.com/ethereum/legacytests/pull/14
=> test: Support withdrawals blockchain tests with fields wider than uint64

lib/evmone_precompiles/blake2b.cpp, test/unittests/precompiles_blake2b_test.cpp
Optimize instrumented build (fuzzer, asan, coverage) of the blake2b precompile by forcing inlining of the helper functions and selectively disabling coverage and undefined behavior sanitizer instrumentation.
=> precompiles: Optimize instrumented blake2b

include/evmmax/evmmax.hpp
In GCC -O2 these two constant-size multiplication loops are not unrolled. For the unrolling in GCC with `#pragma GCC unroll 8`.
=> precompiles: Unroll critical parts of ModArith::mul

lib/evmone_precompiles/modexp.cpp
This is needed for performance edge cases before EIP-7883.
=> precompiles: Instantiate modexp also for 16b inputs

lib/evmone/baseline.hpp, lib/evmone/baseline_analysis.cpp
Construct analyzed code with single allocation. This replaces two allocations: one for the code copy and one for the jumpdest bitset with a single one of the following layout:
- code copy
- code padding (33 bytes)
- alignment padding (0–7 bytes)
- jumpdest bitset with 8-byte words (`ceil(code.size() / 64)` bits)
=> baseline: Optimize code analysis allocation

circle.yml, lib/evmone/instructions.hpp, lib/evmone/instructions_opcodes.hpp, lib/evmone/instructions_traits.hpp, lib/evmone/instructions_xmacro.hpp, test/unittests/CMakeLists.txt, test/unittests/evm_eip7939_clz_test.cpp, test/unittests/instructions_test.cpp, test/utils/bytecode.hpp, test/utils/utils.cpp
fixes:
- https://github.com/ipsilon/evmone/issues/1262
=> EIP-7939: added CLZ opcode for Osaka

circle.yml, test/blockchaintest/blockchaintest_runner.cpp, test/state/block.cpp, test/state/block.hpp, test/statetest/statetest_loader.cpp, test/unittests/statetest_loader_block_info_test.cpp
This implements [EIP-7918](https://eips.ethereum.org/EIPS/eip-7918).
=> Modify blob base fee calculation for Osaka (EIP-7918)

circle.yml
The previously used 2xlarge docker runner is not available in the Circle CI performance plan.
=> ci: Downgrade the clang-tidy job runner

lib/evmone_precompiles/bn254.cpp, lib/evmone_precompiles/bn254.hpp, lib/evmone_precompiles/ecc.hpp, lib/evmone_precompiles/pairing/bn254/fields.hpp, lib/evmone_precompiles/pairing/bn254/utils.hpp, lib/evmone_precompiles/secp256k1.cpp, lib/evmone_precompiles/secp256k1.hpp, test/state/precompiles.cpp, test/state/state.cpp, test/unittests/evmmax_bn254_add_test.cpp, test/unittests/evmmax_bn254_mul_test.cpp, test/unittests/evmmax_bn254_pairing_test.cpp, test/unittests/evmmax_secp256k1_test.cpp
This introduces:
- `struct FieldElement` which wraps the `ModArith` operations. The values of this type always have the Montgomery form to this avoids mistakes in the implementation.
- `struct AffinePoint` which is the pair of `FieldElement` and is the replacement for `Point`.
This improves efficiency also: checking if a point is on curve and doing point multiplication / addition now can easily share the Montgomery form. This improves ecadd precompile performance by 6%.
=> crypto: Add better API for FieldElement and AffinePoint in ECC

lib/evmone_precompiles/bn254.cpp, lib/evmone_precompiles/secp256k1.cpp
These are not needed as the computation will produce correct results.
=> crypto: Remove special case checks from point multiplication

lib/evmone/execution_state.hpp
Use additional wrapping type `StackSpace::Storage` with `alignas(32)` instead of `std::aligned_alloc` to specify the EVM stack space alignment in portable way.
=> Use alignas to specify EVM stack space alignment

lib/evmone_precompiles/bn254.hpp, lib/evmone_precompiles/ecc.hpp
Reduce the scalar by the curve group order.
This allows using more efficient add algorithm in the loop because doubling cannot happen.
=> crypto: Reduce EC multiplication scalar by the order

circle.yml
Use CirleCI self-hosted runner powered by dedicated server for heavy jobs.
Also downgrade macOS jobs to CircleCI free plan.
The UBSan fails because it now executes hardware-accelerated SHA256 implementation. To be fixed later.
=> ci: Switch CircleCI to self-hosted runners

circle.yml
Upgrade EEST test fixture to v5.1.0. Because it also includes Osaka tests the fusaka-devnet-3 tests are disabled.
Moreover, the EEST release includes "static" tests, so we don't differentiate these in the coverage report.
Finally, the coverage report is fixed by providing profile files per test execution tool.
=> ci: Upgrade EEST to v5.1.0

circle.yml, test/blockchaintest/blockchaintest.hpp, test/blockchaintest/blockchaintest_loader.cpp, test/blockchaintest/blockchaintest_runner.cpp, test/unittests/blockchaintest_loader_test.cpp
https://eips.ethereum.org/EIPS/eip-7934
Since `evmone` doesn't decode RLP blocks, but always uses `rlp_decoded`, the `rlp` bytes are not managed, just the size used for the limit check.
=> tests: Support EIP-7934 - MAX_RLP_BLOCK_SIZE
